/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.EmbeddingInferenceProviderID;
import io.swagger.client.model.EmbeddingModelID;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ApplicationEmbeddingTokenEventDataModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class ApplicationEmbeddingTokenEventDataModel {
  @SerializedName("_id")
  private Object _id = null;

  @SerializedName("application_id")
  private Object applicationId = null;

  @SerializedName("tokens")
  private Object tokens = 0;

  @SerializedName("embedding_model_inference_provider_id")
  private EmbeddingInferenceProviderID embeddingModelInferenceProviderId = null;

  @SerializedName("embedding_model_id")
  private EmbeddingModelID embeddingModelId = null;

  @SerializedName("created_at")
  private Object createdAt = null;

  public ApplicationEmbeddingTokenEventDataModel _id(Object _id) {
    this._id = _id;
    return this;
  }

   /**
   * The UUID of this usage event.
   * @return _id
  **/
  @Schema(description = "The UUID of this usage event.")
  public Object getId() {
    return _id;
  }

  public void setId(Object _id) {
    this._id = _id;
  }

  public ApplicationEmbeddingTokenEventDataModel applicationId(Object applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * The UUID of the application associated with this usage event.
   * @return applicationId
  **/
  @Schema(required = true, description = "The UUID of the application associated with this usage event.")
  public Object getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Object applicationId) {
    this.applicationId = applicationId;
  }

  public ApplicationEmbeddingTokenEventDataModel tokens(Object tokens) {
    this.tokens = tokens;
    return this;
  }

   /**
   * The amount of tokens used in this event.
   * @return tokens
  **/
  @Schema(description = "The amount of tokens used in this event.")
  public Object getTokens() {
    return tokens;
  }

  public void setTokens(Object tokens) {
    this.tokens = tokens;
  }

  public ApplicationEmbeddingTokenEventDataModel embeddingModelInferenceProviderId(EmbeddingInferenceProviderID embeddingModelInferenceProviderId) {
    this.embeddingModelInferenceProviderId = embeddingModelInferenceProviderId;
    return this;
  }

   /**
   * The embedding model inference provider used in this event.
   * @return embeddingModelInferenceProviderId
  **/
  @Schema(required = true, description = "The embedding model inference provider used in this event.")
  public EmbeddingInferenceProviderID getEmbeddingModelInferenceProviderId() {
    return embeddingModelInferenceProviderId;
  }

  public void setEmbeddingModelInferenceProviderId(EmbeddingInferenceProviderID embeddingModelInferenceProviderId) {
    this.embeddingModelInferenceProviderId = embeddingModelInferenceProviderId;
  }

  public ApplicationEmbeddingTokenEventDataModel embeddingModelId(EmbeddingModelID embeddingModelId) {
    this.embeddingModelId = embeddingModelId;
    return this;
  }

   /**
   * The embedding model used in this event.
   * @return embeddingModelId
  **/
  @Schema(required = true, description = "The embedding model used in this event.")
  public EmbeddingModelID getEmbeddingModelId() {
    return embeddingModelId;
  }

  public void setEmbeddingModelId(EmbeddingModelID embeddingModelId) {
    this.embeddingModelId = embeddingModelId;
  }

  public ApplicationEmbeddingTokenEventDataModel createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Event creation date.
   * @return createdAt
  **/
  @Schema(description = "Event creation date.")
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationEmbeddingTokenEventDataModel applicationEmbeddingTokenEventDataModel = (ApplicationEmbeddingTokenEventDataModel) o;
    return Objects.equals(this._id, applicationEmbeddingTokenEventDataModel._id) &&
        Objects.equals(this.applicationId, applicationEmbeddingTokenEventDataModel.applicationId) &&
        Objects.equals(this.tokens, applicationEmbeddingTokenEventDataModel.tokens) &&
        Objects.equals(this.embeddingModelInferenceProviderId, applicationEmbeddingTokenEventDataModel.embeddingModelInferenceProviderId) &&
        Objects.equals(this.embeddingModelId, applicationEmbeddingTokenEventDataModel.embeddingModelId) &&
        Objects.equals(this.createdAt, applicationEmbeddingTokenEventDataModel.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, applicationId, tokens, embeddingModelInferenceProviderId, embeddingModelId, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationEmbeddingTokenEventDataModel {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    embeddingModelInferenceProviderId: ").append(toIndentedString(embeddingModelInferenceProviderId)).append("\n");
    sb.append("    embeddingModelId: ").append(toIndentedString(embeddingModelId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
