/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ApplicationQueryPipelineTraceDataModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class ApplicationQueryPipelineTraceDataModel {
  @SerializedName("_id")
  private Object _id = null;

  @SerializedName("application_id")
  private Object applicationId = null;

  @SerializedName("pipeline_trace_events")
  private Object pipelineTraceEvents = [];

  @SerializedName("created_at")
  private Object createdAt = null;

  public ApplicationQueryPipelineTraceDataModel _id(Object _id) {
    this._id = _id;
    return this;
  }

   /**
   * The UUID of this usage event.
   * @return _id
  **/
  @Schema(description = "The UUID of this usage event.")
  public Object getId() {
    return _id;
  }

  public void setId(Object _id) {
    this._id = _id;
  }

  public ApplicationQueryPipelineTraceDataModel applicationId(Object applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * The UUID of the application associated with this usage event.
   * @return applicationId
  **/
  @Schema(required = true, description = "The UUID of the application associated with this usage event.")
  public Object getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Object applicationId) {
    this.applicationId = applicationId;
  }

  public ApplicationQueryPipelineTraceDataModel pipelineTraceEvents(Object pipelineTraceEvents) {
    this.pipelineTraceEvents = pipelineTraceEvents;
    return this;
  }

   /**
   * Get pipelineTraceEvents
   * @return pipelineTraceEvents
  **/
  @Schema(description = "")
  public Object getPipelineTraceEvents() {
    return pipelineTraceEvents;
  }

  public void setPipelineTraceEvents(Object pipelineTraceEvents) {
    this.pipelineTraceEvents = pipelineTraceEvents;
  }

  public ApplicationQueryPipelineTraceDataModel createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Event creation date.
   * @return createdAt
  **/
  @Schema(description = "Event creation date.")
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationQueryPipelineTraceDataModel applicationQueryPipelineTraceDataModel = (ApplicationQueryPipelineTraceDataModel) o;
    return Objects.equals(this._id, applicationQueryPipelineTraceDataModel._id) &&
        Objects.equals(this.applicationId, applicationQueryPipelineTraceDataModel.applicationId) &&
        Objects.equals(this.pipelineTraceEvents, applicationQueryPipelineTraceDataModel.pipelineTraceEvents) &&
        Objects.equals(this.createdAt, applicationQueryPipelineTraceDataModel.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, applicationId, pipelineTraceEvents, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationQueryPipelineTraceDataModel {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    pipelineTraceEvents: ").append(toIndentedString(pipelineTraceEvents)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
