/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ConversationMessageOrigin;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ConversationMessageDataModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class ConversationMessageDataModel {
  @SerializedName("_id")
  private Object _id = null;

  @SerializedName("application_id")
  private Object applicationId = null;

  @SerializedName("conversation_id")
  private Object conversationId = null;

  @SerializedName("corpus_id")
  private Object corpusId = null;

  @SerializedName("origin")
  private ConversationMessageOrigin origin = null;

  @SerializedName("content")
  private Object content = null;

  @SerializedName("response_to_conversation_message_id")
  private Object responseToConversationMessageId = null;

  @SerializedName("non_hallucination_score")
  private Object nonHallucinationScore = 0;

  @SerializedName("factuality_score")
  private Object factualityScore = 0;

  @SerializedName("llm_inference_provider_id")
  private Object llmInferenceProviderId = null;

  @SerializedName("llm_model_id")
  private Object llmModelId = null;

  @SerializedName("reference_object_ids")
  private Object referenceObjectIds = [];

  @SerializedName("created_at")
  private Object createdAt = null;

  public ConversationMessageDataModel _id(Object _id) {
    this._id = _id;
    return this;
  }

   /**
   * The UUID of this conversation message.
   * @return _id
  **/
  @Schema(description = "The UUID of this conversation message.")
  public Object getId() {
    return _id;
  }

  public void setId(Object _id) {
    this._id = _id;
  }

  public ConversationMessageDataModel applicationId(Object applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * The UUID of the application associated with this conversation message.
   * @return applicationId
  **/
  @Schema(required = true, description = "The UUID of the application associated with this conversation message.")
  public Object getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Object applicationId) {
    this.applicationId = applicationId;
  }

  public ConversationMessageDataModel conversationId(Object conversationId) {
    this.conversationId = conversationId;
    return this;
  }

   /**
   * The UUID of the conversation associated with this conversation message.
   * @return conversationId
  **/
  @Schema(required = true, description = "The UUID of the conversation associated with this conversation message.")
  public Object getConversationId() {
    return conversationId;
  }

  public void setConversationId(Object conversationId) {
    this.conversationId = conversationId;
  }

  public ConversationMessageDataModel corpusId(Object corpusId) {
    this.corpusId = corpusId;
    return this;
  }

   /**
   * The UUID of the corpus associated with this conversation message.
   * @return corpusId
  **/
  @Schema(description = "The UUID of the corpus associated with this conversation message.")
  public Object getCorpusId() {
    return corpusId;
  }

  public void setCorpusId(Object corpusId) {
    this.corpusId = corpusId;
  }

  public ConversationMessageDataModel origin(ConversationMessageOrigin origin) {
    this.origin = origin;
    return this;
  }

   /**
   * The origin of this conversation message.
   * @return origin
  **/
  @Schema(required = true, description = "The origin of this conversation message.")
  public ConversationMessageOrigin getOrigin() {
    return origin;
  }

  public void setOrigin(ConversationMessageOrigin origin) {
    this.origin = origin;
  }

  public ConversationMessageDataModel content(Object content) {
    this.content = content;
    return this;
  }

   /**
   * The content of this conversation message.
   * @return content
  **/
  @Schema(required = true, description = "The content of this conversation message.")
  public Object getContent() {
    return content;
  }

  public void setContent(Object content) {
    this.content = content;
  }

  public ConversationMessageDataModel responseToConversationMessageId(Object responseToConversationMessageId) {
    this.responseToConversationMessageId = responseToConversationMessageId;
    return this;
  }

   /**
   * The UUID of the conversation message this one is a response to.
   * @return responseToConversationMessageId
  **/
  @Schema(description = "The UUID of the conversation message this one is a response to.")
  public Object getResponseToConversationMessageId() {
    return responseToConversationMessageId;
  }

  public void setResponseToConversationMessageId(Object responseToConversationMessageId) {
    this.responseToConversationMessageId = responseToConversationMessageId;
  }

  public ConversationMessageDataModel nonHallucinationScore(Object nonHallucinationScore) {
    this.nonHallucinationScore = nonHallucinationScore;
    return this;
  }

   /**
   * How non-hallucinatory the answer is.
   * @return nonHallucinationScore
  **/
  @Schema(description = "How non-hallucinatory the answer is.")
  public Object getNonHallucinationScore() {
    return nonHallucinationScore;
  }

  public void setNonHallucinationScore(Object nonHallucinationScore) {
    this.nonHallucinationScore = nonHallucinationScore;
  }

  public ConversationMessageDataModel factualityScore(Object factualityScore) {
    this.factualityScore = factualityScore;
    return this;
  }

   /**
   * How factual the answer is.
   * @return factualityScore
  **/
  @Schema(description = "How factual the answer is.")
  public Object getFactualityScore() {
    return factualityScore;
  }

  public void setFactualityScore(Object factualityScore) {
    this.factualityScore = factualityScore;
  }

  public ConversationMessageDataModel llmInferenceProviderId(Object llmInferenceProviderId) {
    this.llmInferenceProviderId = llmInferenceProviderId;
    return this;
  }

   /**
   * The LLM inference provider associated with this message.
   * @return llmInferenceProviderId
  **/
  @Schema(description = "The LLM inference provider associated with this message.")
  public Object getLlmInferenceProviderId() {
    return llmInferenceProviderId;
  }

  public void setLlmInferenceProviderId(Object llmInferenceProviderId) {
    this.llmInferenceProviderId = llmInferenceProviderId;
  }

  public ConversationMessageDataModel llmModelId(Object llmModelId) {
    this.llmModelId = llmModelId;
    return this;
  }

   /**
   * The LLM model associated with this message.
   * @return llmModelId
  **/
  @Schema(description = "The LLM model associated with this message.")
  public Object getLlmModelId() {
    return llmModelId;
  }

  public void setLlmModelId(Object llmModelId) {
    this.llmModelId = llmModelId;
  }

  public ConversationMessageDataModel referenceObjectIds(Object referenceObjectIds) {
    this.referenceObjectIds = referenceObjectIds;
    return this;
  }

   /**
   * Reference object UUIDs associated with this conversation message.
   * @return referenceObjectIds
  **/
  @Schema(description = "Reference object UUIDs associated with this conversation message.")
  public Object getReferenceObjectIds() {
    return referenceObjectIds;
  }

  public void setReferenceObjectIds(Object referenceObjectIds) {
    this.referenceObjectIds = referenceObjectIds;
  }

  public ConversationMessageDataModel createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The creation date of this conversation message.
   * @return createdAt
  **/
  @Schema(description = "The creation date of this conversation message.")
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationMessageDataModel conversationMessageDataModel = (ConversationMessageDataModel) o;
    return Objects.equals(this._id, conversationMessageDataModel._id) &&
        Objects.equals(this.applicationId, conversationMessageDataModel.applicationId) &&
        Objects.equals(this.conversationId, conversationMessageDataModel.conversationId) &&
        Objects.equals(this.corpusId, conversationMessageDataModel.corpusId) &&
        Objects.equals(this.origin, conversationMessageDataModel.origin) &&
        Objects.equals(this.content, conversationMessageDataModel.content) &&
        Objects.equals(this.responseToConversationMessageId, conversationMessageDataModel.responseToConversationMessageId) &&
        Objects.equals(this.nonHallucinationScore, conversationMessageDataModel.nonHallucinationScore) &&
        Objects.equals(this.factualityScore, conversationMessageDataModel.factualityScore) &&
        Objects.equals(this.llmInferenceProviderId, conversationMessageDataModel.llmInferenceProviderId) &&
        Objects.equals(this.llmModelId, conversationMessageDataModel.llmModelId) &&
        Objects.equals(this.referenceObjectIds, conversationMessageDataModel.referenceObjectIds) &&
        Objects.equals(this.createdAt, conversationMessageDataModel.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, applicationId, conversationId, corpusId, origin, content, responseToConversationMessageId, nonHallucinationScore, factualityScore, llmInferenceProviderId, llmModelId, referenceObjectIds, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationMessageDataModel {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    conversationId: ").append(toIndentedString(conversationId)).append("\n");
    sb.append("    corpusId: ").append(toIndentedString(corpusId)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    responseToConversationMessageId: ").append(toIndentedString(responseToConversationMessageId)).append("\n");
    sb.append("    nonHallucinationScore: ").append(toIndentedString(nonHallucinationScore)).append("\n");
    sb.append("    factualityScore: ").append(toIndentedString(factualityScore)).append("\n");
    sb.append("    llmInferenceProviderId: ").append(toIndentedString(llmInferenceProviderId)).append("\n");
    sb.append("    llmModelId: ").append(toIndentedString(llmModelId)).append("\n");
    sb.append("    referenceObjectIds: ").append(toIndentedString(referenceObjectIds)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
