/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ConversationDataModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class ConversationDataModel {
  @SerializedName("_id")
  private Object _id = null;

  @SerializedName("application_id")
  private Object applicationId = null;

  @SerializedName("name")
  private Object name = null;

  @SerializedName("created_at")
  private Object createdAt = null;

  public ConversationDataModel _id(Object _id) {
    this._id = _id;
    return this;
  }

   /**
   * The UUID of this session.
   * @return _id
  **/
  @Schema(description = "The UUID of this session.")
  public Object getId() {
    return _id;
  }

  public void setId(Object _id) {
    this._id = _id;
  }

  public ConversationDataModel applicationId(Object applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * The UUID of the application associated with this conversation.
   * @return applicationId
  **/
  @Schema(required = true, description = "The UUID of the application associated with this conversation.")
  public Object getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Object applicationId) {
    this.applicationId = applicationId;
  }

  public ConversationDataModel name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of this conversation.
   * @return name
  **/
  @Schema(required = true, description = "The name of this conversation.")
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public ConversationDataModel createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The creation date of this conversation.
   * @return createdAt
  **/
  @Schema(description = "The creation date of this conversation.")
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationDataModel conversationDataModel = (ConversationDataModel) o;
    return Objects.equals(this._id, conversationDataModel._id) &&
        Objects.equals(this.applicationId, conversationDataModel.applicationId) &&
        Objects.equals(this.name, conversationDataModel.name) &&
        Objects.equals(this.createdAt, conversationDataModel.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, applicationId, name, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationDataModel {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
