/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CorpusDataModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CorpusDataModel {
  @SerializedName("_id")
  private Object _id = null;

  @SerializedName("application_id")
  private Object applicationId = null;

  @SerializedName("name")
  private Object name = null;

  @SerializedName("prompt")
  private Object prompt = null;

  @SerializedName("embedding_inference_provider_id")
  private Object embeddingInferenceProviderId = openai;

  @SerializedName("embedding_model_id")
  private Object embeddingModelId = openai.text-embedding-3-large;

  @SerializedName("created_at")
  private Object createdAt = null;

  public CorpusDataModel _id(Object _id) {
    this._id = _id;
    return this;
  }

   /**
   * The UUID of this corpus.
   * @return _id
  **/
  @Schema(description = "The UUID of this corpus.")
  public Object getId() {
    return _id;
  }

  public void setId(Object _id) {
    this._id = _id;
  }

  public CorpusDataModel applicationId(Object applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * The UUID of the application associated with this corpus.
   * @return applicationId
  **/
  @Schema(required = true, description = "The UUID of the application associated with this corpus.")
  public Object getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Object applicationId) {
    this.applicationId = applicationId;
  }

  public CorpusDataModel name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of this corpus.
   * @return name
  **/
  @Schema(required = true, description = "The name of this corpus.")
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public CorpusDataModel prompt(Object prompt) {
    this.prompt = prompt;
    return this;
  }

   /**
   * System prompt for this corpus.
   * @return prompt
  **/
  @Schema(description = "System prompt for this corpus.")
  public Object getPrompt() {
    return prompt;
  }

  public void setPrompt(Object prompt) {
    this.prompt = prompt;
  }

  public CorpusDataModel embeddingInferenceProviderId(Object embeddingInferenceProviderId) {
    this.embeddingInferenceProviderId = embeddingInferenceProviderId;
    return this;
  }

   /**
   * Embedding inference provider ID
   * @return embeddingInferenceProviderId
  **/
  @Schema(description = "Embedding inference provider ID")
  public Object getEmbeddingInferenceProviderId() {
    return embeddingInferenceProviderId;
  }

  public void setEmbeddingInferenceProviderId(Object embeddingInferenceProviderId) {
    this.embeddingInferenceProviderId = embeddingInferenceProviderId;
  }

  public CorpusDataModel embeddingModelId(Object embeddingModelId) {
    this.embeddingModelId = embeddingModelId;
    return this;
  }

   /**
   * Embedding model ID
   * @return embeddingModelId
  **/
  @Schema(description = "Embedding model ID")
  public Object getEmbeddingModelId() {
    return embeddingModelId;
  }

  public void setEmbeddingModelId(Object embeddingModelId) {
    this.embeddingModelId = embeddingModelId;
  }

  public CorpusDataModel createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Corpus creation date.
   * @return createdAt
  **/
  @Schema(description = "Corpus creation date.")
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorpusDataModel corpusDataModel = (CorpusDataModel) o;
    return Objects.equals(this._id, corpusDataModel._id) &&
        Objects.equals(this.applicationId, corpusDataModel.applicationId) &&
        Objects.equals(this.name, corpusDataModel.name) &&
        Objects.equals(this.prompt, corpusDataModel.prompt) &&
        Objects.equals(this.embeddingInferenceProviderId, corpusDataModel.embeddingInferenceProviderId) &&
        Objects.equals(this.embeddingModelId, corpusDataModel.embeddingModelId) &&
        Objects.equals(this.createdAt, corpusDataModel.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, applicationId, name, prompt, embeddingInferenceProviderId, embeddingModelId, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorpusDataModel {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    embeddingInferenceProviderId: ").append(toIndentedString(embeddingInferenceProviderId)).append("\n");
    sb.append("    embeddingModelId: ").append(toIndentedString(embeddingModelId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
