/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateLLMCompletionRequestModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateLLMCompletionRequestModel {
  @SerializedName("prompt")
  private Object prompt = null;

  @SerializedName("temperature")
  private Object temperature = 0.8;

  @SerializedName("output_schema")
  private Object outputSchema = null;

  public CreateLLMCompletionRequestModel prompt(Object prompt) {
    this.prompt = prompt;
    return this;
  }

   /**
   * Semantic/keyword based prompt.
   * @return prompt
  **/
  @Schema(required = true, description = "Semantic/keyword based prompt.")
  public Object getPrompt() {
    return prompt;
  }

  public void setPrompt(Object prompt) {
    this.prompt = prompt;
  }

  public CreateLLMCompletionRequestModel temperature(Object temperature) {
    this.temperature = temperature;
    return this;
  }

   /**
   * LLM model temperature
   * @return temperature
  **/
  @Schema(description = "LLM model temperature")
  public Object getTemperature() {
    return temperature;
  }

  public void setTemperature(Object temperature) {
    this.temperature = temperature;
  }

  public CreateLLMCompletionRequestModel outputSchema(Object outputSchema) {
    this.outputSchema = outputSchema;
    return this;
  }

   /**
   * Optional output schema -                          see https://python.langchain.com/docs/how_to/structured_output/#the-with_structured_output-method for more information.                     
   * @return outputSchema
  **/
  @Schema(description = "Optional output schema -                          see https://python.langchain.com/docs/how_to/structured_output/#the-with_structured_output-method for more information.                     ")
  public Object getOutputSchema() {
    return outputSchema;
  }

  public void setOutputSchema(Object outputSchema) {
    this.outputSchema = outputSchema;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLLMCompletionRequestModel createLLMCompletionRequestModel = (CreateLLMCompletionRequestModel) o;
    return Objects.equals(this.prompt, createLLMCompletionRequestModel.prompt) &&
        Objects.equals(this.temperature, createLLMCompletionRequestModel.temperature) &&
        Objects.equals(this.outputSchema, createLLMCompletionRequestModel.outputSchema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompt, temperature, outputSchema);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLLMCompletionRequestModel {\n");
    
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    outputSchema: ").append(toIndentedString(outputSchema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
