/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateReferenceObjectSearchRequestModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateReferenceObjectSearchRequestModel {
  @SerializedName("prompt")
  private Object prompt = null;

  @SerializedName("include_reference_objects")
  private Object includeReferenceObjects = null;

  public CreateReferenceObjectSearchRequestModel prompt(Object prompt) {
    this.prompt = prompt;
    return this;
  }

   /**
   * Semantic/keyword based prompt.
   * @return prompt
  **/
  @Schema(required = true, description = "Semantic/keyword based prompt.")
  public Object getPrompt() {
    return prompt;
  }

  public void setPrompt(Object prompt) {
    this.prompt = prompt;
  }

  public CreateReferenceObjectSearchRequestModel includeReferenceObjects(Object includeReferenceObjects) {
    this.includeReferenceObjects = includeReferenceObjects;
    return this;
  }

   /**
   * Explicitly include specified reference objects when searching. Setting this will limit search only to reference objects specified here.
   * @return includeReferenceObjects
  **/
  @Schema(description = "Explicitly include specified reference objects when searching. Setting this will limit search only to reference objects specified here.")
  public Object getIncludeReferenceObjects() {
    return includeReferenceObjects;
  }

  public void setIncludeReferenceObjects(Object includeReferenceObjects) {
    this.includeReferenceObjects = includeReferenceObjects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateReferenceObjectSearchRequestModel createReferenceObjectSearchRequestModel = (CreateReferenceObjectSearchRequestModel) o;
    return Objects.equals(this.prompt, createReferenceObjectSearchRequestModel.prompt) &&
        Objects.equals(this.includeReferenceObjects, createReferenceObjectSearchRequestModel.includeReferenceObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompt, includeReferenceObjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReferenceObjectSearchRequestModel {\n");
    
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    includeReferenceObjects: ").append(toIndentedString(includeReferenceObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
