/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ApplicationDataModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateApplicationResponseModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateApplicationResponseModel {
  @SerializedName("application")
  private ApplicationDataModel application = null;

  public CreateApplicationResponseModel application(ApplicationDataModel application) {
    this.application = application;
    return this;
  }

   /**
   * The application that was created in this request.
   * @return application
  **/
  @Schema(required = true, description = "The application that was created in this request.")
  public ApplicationDataModel getApplication() {
    return application;
  }

  public void setApplication(ApplicationDataModel application) {
    this.application = application;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateApplicationResponseModel createApplicationResponseModel = (CreateApplicationResponseModel) o;
    return Objects.equals(this.application, createApplicationResponseModel.application);
  }

  @Override
  public int hashCode() {
    return Objects.hash(application);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateApplicationResponseModel {\n");
    
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
