/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateConversationMessageRequestModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateConversationMessageRequestModel {
  @SerializedName("content")
  private Object content = null;

  @SerializedName("corpus_id")
  private Object corpusId = null;

  @SerializedName("include_reference_objects")
  private Object includeReferenceObjects = [];

  @SerializedName("factuality_mode")
  private Object factualityMode = grounded;

  @SerializedName("temperature")
  private Object temperature = 0.8;

  @SerializedName("with_pipeline_trace")
  private Object withPipelineTrace = false;

  @SerializedName("llm_inference_provider_id")
  private Object llmInferenceProviderId = vertex-ai;

  @SerializedName("llm_model_id")
  private Object llmModelId = vertex-ai.gemini-2.0-pro;

  public CreateConversationMessageRequestModel content(Object content) {
    this.content = content;
    return this;
  }

   /**
   * Semantic/keyword based prompt.
   * @return content
  **/
  @Schema(required = true, description = "Semantic/keyword based prompt.")
  public Object getContent() {
    return content;
  }

  public void setContent(Object content) {
    this.content = content;
  }

  public CreateConversationMessageRequestModel corpusId(Object corpusId) {
    this.corpusId = corpusId;
    return this;
  }

   /**
   * The corpus to query.
   * @return corpusId
  **/
  @Schema(description = "The corpus to query.")
  public Object getCorpusId() {
    return corpusId;
  }

  public void setCorpusId(Object corpusId) {
    this.corpusId = corpusId;
  }

  public CreateConversationMessageRequestModel includeReferenceObjects(Object includeReferenceObjects) {
    this.includeReferenceObjects = includeReferenceObjects;
    return this;
  }

   /**
   * Explicitly include specified reference objects when searching.                     Setting this will limit search only to reference objects specified here.
   * @return includeReferenceObjects
  **/
  @Schema(description = "Explicitly include specified reference objects when searching.                     Setting this will limit search only to reference objects specified here.")
  public Object getIncludeReferenceObjects() {
    return includeReferenceObjects;
  }

  public void setIncludeReferenceObjects(Object includeReferenceObjects) {
    this.includeReferenceObjects = includeReferenceObjects;
  }

  public CreateConversationMessageRequestModel factualityMode(Object factualityMode) {
    this.factualityMode = factualityMode;
    return this;
  }

   /**
   * The factuality mode requested.
   * @return factualityMode
  **/
  @Schema(description = "The factuality mode requested.")
  public Object getFactualityMode() {
    return factualityMode;
  }

  public void setFactualityMode(Object factualityMode) {
    this.factualityMode = factualityMode;
  }

  public CreateConversationMessageRequestModel temperature(Object temperature) {
    this.temperature = temperature;
    return this;
  }

   /**
   * LLM model temperature.
   * @return temperature
  **/
  @Schema(description = "LLM model temperature.")
  public Object getTemperature() {
    return temperature;
  }

  public void setTemperature(Object temperature) {
    this.temperature = temperature;
  }

  public CreateConversationMessageRequestModel withPipelineTrace(Object withPipelineTrace) {
    this.withPipelineTrace = withPipelineTrace;
    return this;
  }

   /**
   * Include the pipeline trace.
   * @return withPipelineTrace
  **/
  @Schema(description = "Include the pipeline trace.")
  public Object getWithPipelineTrace() {
    return withPipelineTrace;
  }

  public void setWithPipelineTrace(Object withPipelineTrace) {
    this.withPipelineTrace = withPipelineTrace;
  }

  public CreateConversationMessageRequestModel llmInferenceProviderId(Object llmInferenceProviderId) {
    this.llmInferenceProviderId = llmInferenceProviderId;
    return this;
  }

   /**
   * The LLM inference provider to use.
   * @return llmInferenceProviderId
  **/
  @Schema(description = "The LLM inference provider to use.")
  public Object getLlmInferenceProviderId() {
    return llmInferenceProviderId;
  }

  public void setLlmInferenceProviderId(Object llmInferenceProviderId) {
    this.llmInferenceProviderId = llmInferenceProviderId;
  }

  public CreateConversationMessageRequestModel llmModelId(Object llmModelId) {
    this.llmModelId = llmModelId;
    return this;
  }

   /**
   * The LLM model to use.
   * @return llmModelId
  **/
  @Schema(description = "The LLM model to use.")
  public Object getLlmModelId() {
    return llmModelId;
  }

  public void setLlmModelId(Object llmModelId) {
    this.llmModelId = llmModelId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateConversationMessageRequestModel createConversationMessageRequestModel = (CreateConversationMessageRequestModel) o;
    return Objects.equals(this.content, createConversationMessageRequestModel.content) &&
        Objects.equals(this.corpusId, createConversationMessageRequestModel.corpusId) &&
        Objects.equals(this.includeReferenceObjects, createConversationMessageRequestModel.includeReferenceObjects) &&
        Objects.equals(this.factualityMode, createConversationMessageRequestModel.factualityMode) &&
        Objects.equals(this.temperature, createConversationMessageRequestModel.temperature) &&
        Objects.equals(this.withPipelineTrace, createConversationMessageRequestModel.withPipelineTrace) &&
        Objects.equals(this.llmInferenceProviderId, createConversationMessageRequestModel.llmInferenceProviderId) &&
        Objects.equals(this.llmModelId, createConversationMessageRequestModel.llmModelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, corpusId, includeReferenceObjects, factualityMode, temperature, withPipelineTrace, llmInferenceProviderId, llmModelId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateConversationMessageRequestModel {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    corpusId: ").append(toIndentedString(corpusId)).append("\n");
    sb.append("    includeReferenceObjects: ").append(toIndentedString(includeReferenceObjects)).append("\n");
    sb.append("    factualityMode: ").append(toIndentedString(factualityMode)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    withPipelineTrace: ").append(toIndentedString(withPipelineTrace)).append("\n");
    sb.append("    llmInferenceProviderId: ").append(toIndentedString(llmInferenceProviderId)).append("\n");
    sb.append("    llmModelId: ").append(toIndentedString(llmModelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
