/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LLMInferenceProviderID;
import io.swagger.client.model.LLMModelID;
import io.swagger.client.model.UsageInfoModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateLLMCompletionResponseModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateLLMCompletionResponseModel {
  @SerializedName("llm_inference_provider_id")
  private LLMInferenceProviderID llmInferenceProviderId = null;

  @SerializedName("llm_model_id")
  private LLMModelID llmModelId = null;

  @SerializedName("content")
  private Object content = null;

  @SerializedName("usage_info")
  private UsageInfoModel usageInfo = null;

  public CreateLLMCompletionResponseModel llmInferenceProviderId(LLMInferenceProviderID llmInferenceProviderId) {
    this.llmInferenceProviderId = llmInferenceProviderId;
    return this;
  }

   /**
   * Used LLM inference provider.
   * @return llmInferenceProviderId
  **/
  @Schema(required = true, description = "Used LLM inference provider.")
  public LLMInferenceProviderID getLlmInferenceProviderId() {
    return llmInferenceProviderId;
  }

  public void setLlmInferenceProviderId(LLMInferenceProviderID llmInferenceProviderId) {
    this.llmInferenceProviderId = llmInferenceProviderId;
  }

  public CreateLLMCompletionResponseModel llmModelId(LLMModelID llmModelId) {
    this.llmModelId = llmModelId;
    return this;
  }

   /**
   * Used LLM inference provider.
   * @return llmModelId
  **/
  @Schema(required = true, description = "Used LLM inference provider.")
  public LLMModelID getLlmModelId() {
    return llmModelId;
  }

  public void setLlmModelId(LLMModelID llmModelId) {
    this.llmModelId = llmModelId;
  }

  public CreateLLMCompletionResponseModel content(Object content) {
    this.content = content;
    return this;
  }

   /**
   * The response from the LLM.
   * @return content
  **/
  @Schema(required = true, description = "The response from the LLM.")
  public Object getContent() {
    return content;
  }

  public void setContent(Object content) {
    this.content = content;
  }

  public CreateLLMCompletionResponseModel usageInfo(UsageInfoModel usageInfo) {
    this.usageInfo = usageInfo;
    return this;
  }

   /**
   * Request usage information.
   * @return usageInfo
  **/
  @Schema(required = true, description = "Request usage information.")
  public UsageInfoModel getUsageInfo() {
    return usageInfo;
  }

  public void setUsageInfo(UsageInfoModel usageInfo) {
    this.usageInfo = usageInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLLMCompletionResponseModel createLLMCompletionResponseModel = (CreateLLMCompletionResponseModel) o;
    return Objects.equals(this.llmInferenceProviderId, createLLMCompletionResponseModel.llmInferenceProviderId) &&
        Objects.equals(this.llmModelId, createLLMCompletionResponseModel.llmModelId) &&
        Objects.equals(this.content, createLLMCompletionResponseModel.content) &&
        Objects.equals(this.usageInfo, createLLMCompletionResponseModel.usageInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(llmInferenceProviderId, llmModelId, content, usageInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLLMCompletionResponseModel {\n");
    
    sb.append("    llmInferenceProviderId: ").append(toIndentedString(llmInferenceProviderId)).append("\n");
    sb.append("    llmModelId: ").append(toIndentedString(llmModelId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    usageInfo: ").append(toIndentedString(usageInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
