/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateReferenceObjectSearchResponseModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateReferenceObjectSearchResponseModel {
  @SerializedName("reference_object_excerpts")
  private Object referenceObjectExcerpts = null;

  public CreateReferenceObjectSearchResponseModel referenceObjectExcerpts(Object referenceObjectExcerpts) {
    this.referenceObjectExcerpts = referenceObjectExcerpts;
    return this;
  }

   /**
   * A list of excerpts from reference objects matching search parameters.
   * @return referenceObjectExcerpts
  **/
  @Schema(required = true, description = "A list of excerpts from reference objects matching search parameters.")
  public Object getReferenceObjectExcerpts() {
    return referenceObjectExcerpts;
  }

  public void setReferenceObjectExcerpts(Object referenceObjectExcerpts) {
    this.referenceObjectExcerpts = referenceObjectExcerpts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateReferenceObjectSearchResponseModel createReferenceObjectSearchResponseModel = (CreateReferenceObjectSearchResponseModel) o;
    return Objects.equals(this.referenceObjectExcerpts, createReferenceObjectSearchResponseModel.referenceObjectExcerpts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceObjectExcerpts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReferenceObjectSearchResponseModel {\n");
    
    sb.append("    referenceObjectExcerpts: ").append(toIndentedString(referenceObjectExcerpts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
