/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateCorpusRequestModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateCorpusRequestModel {
  @SerializedName("name")
  private Object name = null;

  @SerializedName("prompt")
  private Object prompt = null;

  @SerializedName("embedding_inference_provider_id")
  private Object embeddingInferenceProviderId = openai;

  @SerializedName("embedding_model_id")
  private Object embeddingModelId = openai.text-embedding-3-large;

  public CreateCorpusRequestModel name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of this corpus.
   * @return name
  **/
  @Schema(required = true, description = "The name of this corpus.")
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public CreateCorpusRequestModel prompt(Object prompt) {
    this.prompt = prompt;
    return this;
  }

   /**
   * System prompt for this corpus.
   * @return prompt
  **/
  @Schema(description = "System prompt for this corpus.")
  public Object getPrompt() {
    return prompt;
  }

  public void setPrompt(Object prompt) {
    this.prompt = prompt;
  }

  public CreateCorpusRequestModel embeddingInferenceProviderId(Object embeddingInferenceProviderId) {
    this.embeddingInferenceProviderId = embeddingInferenceProviderId;
    return this;
  }

   /**
   * Embedding inference provider ID
   * @return embeddingInferenceProviderId
  **/
  @Schema(description = "Embedding inference provider ID")
  public Object getEmbeddingInferenceProviderId() {
    return embeddingInferenceProviderId;
  }

  public void setEmbeddingInferenceProviderId(Object embeddingInferenceProviderId) {
    this.embeddingInferenceProviderId = embeddingInferenceProviderId;
  }

  public CreateCorpusRequestModel embeddingModelId(Object embeddingModelId) {
    this.embeddingModelId = embeddingModelId;
    return this;
  }

   /**
   * Embedding model ID
   * @return embeddingModelId
  **/
  @Schema(description = "Embedding model ID")
  public Object getEmbeddingModelId() {
    return embeddingModelId;
  }

  public void setEmbeddingModelId(Object embeddingModelId) {
    this.embeddingModelId = embeddingModelId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCorpusRequestModel createCorpusRequestModel = (CreateCorpusRequestModel) o;
    return Objects.equals(this.name, createCorpusRequestModel.name) &&
        Objects.equals(this.prompt, createCorpusRequestModel.prompt) &&
        Objects.equals(this.embeddingInferenceProviderId, createCorpusRequestModel.embeddingInferenceProviderId) &&
        Objects.equals(this.embeddingModelId, createCorpusRequestModel.embeddingModelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, prompt, embeddingInferenceProviderId, embeddingModelId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCorpusRequestModel {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    embeddingInferenceProviderId: ").append(toIndentedString(embeddingInferenceProviderId)).append("\n");
    sb.append("    embeddingModelId: ").append(toIndentedString(embeddingModelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
