/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateOrganizationRequestModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class CreateOrganizationRequestModel {
  @SerializedName("name")
  private Object name = null;

  @SerializedName("email")
  private Object email = null;

  @SerializedName("is_active")
  private Object isActive = true;

  @SerializedName("billing_lock")
  private Object billingLock = false;

  public CreateOrganizationRequestModel name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of this organization.
   * @return name
  **/
  @Schema(required = true, description = "The name of this organization.")
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public CreateOrganizationRequestModel email(Object email) {
    this.email = email;
    return this;
  }

   /**
   * Email address of the contact person associated with this organization.
   * @return email
  **/
  @Schema(required = true, description = "Email address of the contact person associated with this organization.")
  public Object getEmail() {
    return email;
  }

  public void setEmail(Object email) {
    this.email = email;
  }

  public CreateOrganizationRequestModel isActive(Object isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Is this organization active?
   * @return isActive
  **/
  @Schema(description = "Is this organization active?")
  public Object getIsActive() {
    return isActive;
  }

  public void setIsActive(Object isActive) {
    this.isActive = isActive;
  }

  public CreateOrganizationRequestModel billingLock(Object billingLock) {
    this.billingLock = billingLock;
    return this;
  }

   /**
   * Does this organization have a billing lock?
   * @return billingLock
  **/
  @Schema(description = "Does this organization have a billing lock?")
  public Object getBillingLock() {
    return billingLock;
  }

  public void setBillingLock(Object billingLock) {
    this.billingLock = billingLock;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrganizationRequestModel createOrganizationRequestModel = (CreateOrganizationRequestModel) o;
    return Objects.equals(this.name, createOrganizationRequestModel.name) &&
        Objects.equals(this.email, createOrganizationRequestModel.email) &&
        Objects.equals(this.isActive, createOrganizationRequestModel.isActive) &&
        Objects.equals(this.billingLock, createOrganizationRequestModel.billingLock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, isActive, billingLock);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrganizationRequestModel {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    billingLock: ").append(toIndentedString(billingLock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
