/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ListEmbeddingInferenceProviderModelsResponseModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class ListEmbeddingInferenceProviderModelsResponseModel {
  @SerializedName("embedding_models")
  private Object embeddingModels = null;

  public ListEmbeddingInferenceProviderModelsResponseModel embeddingModels(Object embeddingModels) {
    this.embeddingModels = embeddingModels;
    return this;
  }

   /**
   * The list of all embeddings supported by this inference provider along with their dimensions.
   * @return embeddingModels
  **/
  @Schema(required = true, description = "The list of all embeddings supported by this inference provider along with their dimensions.")
  public Object getEmbeddingModels() {
    return embeddingModels;
  }

  public void setEmbeddingModels(Object embeddingModels) {
    this.embeddingModels = embeddingModels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListEmbeddingInferenceProviderModelsResponseModel listEmbeddingInferenceProviderModelsResponseModel = (ListEmbeddingInferenceProviderModelsResponseModel) o;
    return Objects.equals(this.embeddingModels, listEmbeddingInferenceProviderModelsResponseModel.embeddingModels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(embeddingModels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListEmbeddingInferenceProviderModelsResponseModel {\n");
    
    sb.append("    embeddingModels: ").append(toIndentedString(embeddingModels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
