/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets LLMLanguage
 */
@JsonAdapter(LLMLanguage.Adapter.class)
public enum LLMLanguage {
  @SerializedName("english")
  ENGLISH("english"),
  @SerializedName("chinese")
  CHINESE("chinese"),
  @SerializedName("japanese")
  JAPANESE("japanese"),
  @SerializedName("korean")
  KOREAN("korean"),
  @SerializedName("polish")
  POLISH("polish"),
  @SerializedName("spanish")
  SPANISH("spanish"),
  @SerializedName("german")
  GERMAN("german"),
  @SerializedName("french")
  FRENCH("french"),
  @SerializedName("italian")
  ITALIAN("italian"),
  @SerializedName("portuguese")
  PORTUGUESE("portuguese"),
  @SerializedName("arabic")
  ARABIC("arabic"),
  @SerializedName("hindi")
  HINDI("hindi"),
  @SerializedName("others")
  OTHERS("others");

  private Object value;

  LLMLanguage(Object value) {
    this.value = value;
  }

  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LLMLanguage fromValue(Object input) {
    for (LLMLanguage b : LLMLanguage.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<LLMLanguage> {
    @Override
    public void write(final JsonWriter jsonWriter, final LLMLanguage enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public LLMLanguage read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return LLMLanguage.fromValue((Object)(value));
    }
  }
}
