/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LLMModelInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class LLMModelInfo {
  @SerializedName("context_window_size")
  private Object contextWindowSize = null;

  @SerializedName("supported_languages")
  private Object supportedLanguages = ["english","chinese","japanese","korean","polish","spanish","german","french","italian","portuguese","arabic","hindi","others"];

  @SerializedName("is_expensive")
  private Object isExpensive = false;

  @SerializedName("is_reasoning")
  private Object isReasoning = false;

  @SerializedName("is_vision")
  private Object isVision = false;

  @SerializedName("supports_structured_output")
  private Object supportsStructuredOutput = false;

  @SerializedName("requires_local_inference")
  private Object requiresLocalInference = false;

  public LLMModelInfo contextWindowSize(Object contextWindowSize) {
    this.contextWindowSize = contextWindowSize;
    return this;
  }

   /**
   * The size of the context window.
   * @return contextWindowSize
  **/
  @Schema(required = true, description = "The size of the context window.")
  public Object getContextWindowSize() {
    return contextWindowSize;
  }

  public void setContextWindowSize(Object contextWindowSize) {
    this.contextWindowSize = contextWindowSize;
  }

  public LLMModelInfo supportedLanguages(Object supportedLanguages) {
    this.supportedLanguages = supportedLanguages;
    return this;
  }

   /**
   * Languages supported by the LLM.
   * @return supportedLanguages
  **/
  @Schema(description = "Languages supported by the LLM.")
  public Object getSupportedLanguages() {
    return supportedLanguages;
  }

  public void setSupportedLanguages(Object supportedLanguages) {
    this.supportedLanguages = supportedLanguages;
  }

  public LLMModelInfo isExpensive(Object isExpensive) {
    this.isExpensive = isExpensive;
    return this;
  }

   /**
   * Is this model expensive to run?
   * @return isExpensive
  **/
  @Schema(description = "Is this model expensive to run?")
  public Object getIsExpensive() {
    return isExpensive;
  }

  public void setIsExpensive(Object isExpensive) {
    this.isExpensive = isExpensive;
  }

  public LLMModelInfo isReasoning(Object isReasoning) {
    this.isReasoning = isReasoning;
    return this;
  }

   /**
   * Is this a reasoning model?
   * @return isReasoning
  **/
  @Schema(description = "Is this a reasoning model?")
  public Object getIsReasoning() {
    return isReasoning;
  }

  public void setIsReasoning(Object isReasoning) {
    this.isReasoning = isReasoning;
  }

  public LLMModelInfo isVision(Object isVision) {
    this.isVision = isVision;
    return this;
  }

   /**
   * Is this a vision model?
   * @return isVision
  **/
  @Schema(description = "Is this a vision model?")
  public Object getIsVision() {
    return isVision;
  }

  public void setIsVision(Object isVision) {
    this.isVision = isVision;
  }

  public LLMModelInfo supportsStructuredOutput(Object supportsStructuredOutput) {
    this.supportsStructuredOutput = supportsStructuredOutput;
    return this;
  }

   /**
   * Does this model support structured output?
   * @return supportsStructuredOutput
  **/
  @Schema(description = "Does this model support structured output?")
  public Object getSupportsStructuredOutput() {
    return supportsStructuredOutput;
  }

  public void setSupportsStructuredOutput(Object supportsStructuredOutput) {
    this.supportsStructuredOutput = supportsStructuredOutput;
  }

  public LLMModelInfo requiresLocalInference(Object requiresLocalInference) {
    this.requiresLocalInference = requiresLocalInference;
    return this;
  }

   /**
   * Does this model require local inference?
   * @return requiresLocalInference
  **/
  @Schema(description = "Does this model require local inference?")
  public Object getRequiresLocalInference() {
    return requiresLocalInference;
  }

  public void setRequiresLocalInference(Object requiresLocalInference) {
    this.requiresLocalInference = requiresLocalInference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LLMModelInfo llMModelInfo = (LLMModelInfo) o;
    return Objects.equals(this.contextWindowSize, llMModelInfo.contextWindowSize) &&
        Objects.equals(this.supportedLanguages, llMModelInfo.supportedLanguages) &&
        Objects.equals(this.isExpensive, llMModelInfo.isExpensive) &&
        Objects.equals(this.isReasoning, llMModelInfo.isReasoning) &&
        Objects.equals(this.isVision, llMModelInfo.isVision) &&
        Objects.equals(this.supportsStructuredOutput, llMModelInfo.supportsStructuredOutput) &&
        Objects.equals(this.requiresLocalInference, llMModelInfo.requiresLocalInference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contextWindowSize, supportedLanguages, isExpensive, isReasoning, isVision, supportsStructuredOutput, requiresLocalInference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LLMModelInfo {\n");
    
    sb.append("    contextWindowSize: ").append(toIndentedString(contextWindowSize)).append("\n");
    sb.append("    supportedLanguages: ").append(toIndentedString(supportedLanguages)).append("\n");
    sb.append("    isExpensive: ").append(toIndentedString(isExpensive)).append("\n");
    sb.append("    isReasoning: ").append(toIndentedString(isReasoning)).append("\n");
    sb.append("    isVision: ").append(toIndentedString(isVision)).append("\n");
    sb.append("    supportsStructuredOutput: ").append(toIndentedString(supportsStructuredOutput)).append("\n");
    sb.append("    requiresLocalInference: ").append(toIndentedString(requiresLocalInference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
