/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets LLMModelID
 */
@JsonAdapter(LLMModelID.Adapter.class)
public enum LLMModelID {
  @SerializedName("default")
  DEFAULT("default"),
  @SerializedName("anthropic.claude-3.7-sonnet")
  ANTHROPIC_CLAUDE_3_7_SONNET("anthropic.claude-3.7-sonnet"),
  @SerializedName("anthropic.claude-3.5-sonnet")
  ANTHROPIC_CLAUDE_3_5_SONNET("anthropic.claude-3.5-sonnet"),
  @SerializedName("anthropic.claude-3.5-haiku")
  ANTHROPIC_CLAUDE_3_5_HAIKU("anthropic.claude-3.5-haiku"),
  @SerializedName("azure-openai.gpt-4.5")
  AZURE_OPENAI_GPT_4_5("azure-openai.gpt-4.5"),
  @SerializedName("azure-openai.gpt-4-turbo")
  AZURE_OPENAI_GPT_4_TURBO("azure-openai.gpt-4-turbo"),
  @SerializedName("azure-openai.gpt-4o")
  AZURE_OPENAI_GPT_4O("azure-openai.gpt-4o"),
  @SerializedName("azure-openai.gpt-4o-mini")
  AZURE_OPENAI_GPT_4O_MINI("azure-openai.gpt-4o-mini"),
  @SerializedName("azure-openai.o1")
  AZURE_OPENAI_O1("azure-openai.o1"),
  @SerializedName("azure-openai.o3-mini")
  AZURE_OPENAI_O3_MINI("azure-openai.o3-mini"),
  @SerializedName("openai.gpt-4.5")
  OPENAI_GPT_4_5("openai.gpt-4.5"),
  @SerializedName("openai.gpt-4-turbo")
  OPENAI_GPT_4_TURBO("openai.gpt-4-turbo"),
  @SerializedName("openai.gpt-4o")
  OPENAI_GPT_4O("openai.gpt-4o"),
  @SerializedName("openai.gpt-4o-mini")
  OPENAI_GPT_4O_MINI("openai.gpt-4o-mini"),
  @SerializedName("openai.o1")
  OPENAI_O1("openai.o1"),
  @SerializedName("openai.o3-mini")
  OPENAI_O3_MINI("openai.o3-mini"),
  @SerializedName("bedrock.claude-3.7-sonnet")
  BEDROCK_CLAUDE_3_7_SONNET("bedrock.claude-3.7-sonnet"),
  @SerializedName("bedrock.claude-3.5-sonnet")
  BEDROCK_CLAUDE_3_5_SONNET("bedrock.claude-3.5-sonnet"),
  @SerializedName("bedrock.claude-3.5-haiku")
  BEDROCK_CLAUDE_3_5_HAIKU("bedrock.claude-3.5-haiku"),
  @SerializedName("bedrock.llama-3.1-8b")
  BEDROCK_LLAMA_3_1_8B("bedrock.llama-3.1-8b"),
  @SerializedName("bedrock.llama-3.1-70b")
  BEDROCK_LLAMA_3_1_70B("bedrock.llama-3.1-70b"),
  @SerializedName("bedrock.llama-3.1-405b")
  BEDROCK_LLAMA_3_1_405B("bedrock.llama-3.1-405b"),
  @SerializedName("bedrock.llama-3.2-1b")
  BEDROCK_LLAMA_3_2_1B("bedrock.llama-3.2-1b"),
  @SerializedName("bedrock.llama-3.2-3b")
  BEDROCK_LLAMA_3_2_3B("bedrock.llama-3.2-3b"),
  @SerializedName("bedrock.llama-3.2-11b")
  BEDROCK_LLAMA_3_2_11B("bedrock.llama-3.2-11b"),
  @SerializedName("bedrock.llama-3.2-90b")
  BEDROCK_LLAMA_3_2_90B("bedrock.llama-3.2-90b"),
  @SerializedName("bedrock.llama-3.3-70b")
  BEDROCK_LLAMA_3_3_70B("bedrock.llama-3.3-70b"),
  @SerializedName("bedrock.mistral-7b")
  BEDROCK_MISTRAL_7B("bedrock.mistral-7b"),
  @SerializedName("bedrock.mistral-large")
  BEDROCK_MISTRAL_LARGE("bedrock.mistral-large"),
  @SerializedName("bedrock.mistral-small")
  BEDROCK_MISTRAL_SMALL("bedrock.mistral-small"),
  @SerializedName("mistral-ai.mistral-large")
  MISTRAL_AI_MISTRAL_LARGE("mistral-ai.mistral-large"),
  @SerializedName("mistral-ai.mistral-small")
  MISTRAL_AI_MISTRAL_SMALL("mistral-ai.mistral-small"),
  @SerializedName("mistral-ai.mistral-saba")
  MISTRAL_AI_MISTRAL_SABA("mistral-ai.mistral-saba"),
  @SerializedName("ollama.deepseek-r1-7b")
  OLLAMA_DEEPSEEK_R1_7B("ollama.deepseek-r1-7b"),
  @SerializedName("ollama.deepseek-r1-8b")
  OLLAMA_DEEPSEEK_R1_8B("ollama.deepseek-r1-8b"),
  @SerializedName("ollama.deepseek-r1-14b")
  OLLAMA_DEEPSEEK_R1_14B("ollama.deepseek-r1-14b"),
  @SerializedName("ollama.deepseek-r1-32b")
  OLLAMA_DEEPSEEK_R1_32B("ollama.deepseek-r1-32b"),
  @SerializedName("ollama.deepseek-r1-70b")
  OLLAMA_DEEPSEEK_R1_70B("ollama.deepseek-r1-70b"),
  @SerializedName("ollama.deepseek-r1-405b")
  OLLAMA_DEEPSEEK_R1_405B("ollama.deepseek-r1-405b"),
  @SerializedName("ollama.llama-3.1-8b")
  OLLAMA_LLAMA_3_1_8B("ollama.llama-3.1-8b"),
  @SerializedName("ollama.llama-3.1-70b")
  OLLAMA_LLAMA_3_1_70B("ollama.llama-3.1-70b"),
  @SerializedName("ollama.llama-3.1-405b")
  OLLAMA_LLAMA_3_1_405B("ollama.llama-3.1-405b"),
  @SerializedName("ollama.llama-3.2-1b")
  OLLAMA_LLAMA_3_2_1B("ollama.llama-3.2-1b"),
  @SerializedName("ollama.llama-3.2-3b")
  OLLAMA_LLAMA_3_2_3B("ollama.llama-3.2-3b"),
  @SerializedName("ollama.llama-3.3-70b")
  OLLAMA_LLAMA_3_3_70B("ollama.llama-3.3-70b"),
  @SerializedName("ollama.qwen-2.5-3b")
  OLLAMA_QWEN_2_5_3B("ollama.qwen-2.5-3b"),
  @SerializedName("ollama.qwen-2.5-7b")
  OLLAMA_QWEN_2_5_7B("ollama.qwen-2.5-7b"),
  @SerializedName("ollama.qwen-2.5-14b")
  OLLAMA_QWEN_2_5_14B("ollama.qwen-2.5-14b"),
  @SerializedName("ollama.qwen-2.5-32b")
  OLLAMA_QWEN_2_5_32B("ollama.qwen-2.5-32b"),
  @SerializedName("ollama.qwen-2.5-72b")
  OLLAMA_QWEN_2_5_72B("ollama.qwen-2.5-72b"),
  @SerializedName("ollama.phi4")
  OLLAMA_PHI4("ollama.phi4"),
  @SerializedName("together.llama-3.1-8b")
  TOGETHER_LLAMA_3_1_8B("together.llama-3.1-8b"),
  @SerializedName("together.llama-3.1-405b")
  TOGETHER_LLAMA_3_1_405B("together.llama-3.1-405b"),
  @SerializedName("together.llama-3.2-11b")
  TOGETHER_LLAMA_3_2_11B("together.llama-3.2-11b"),
  @SerializedName("together.llama-3.2-90b")
  TOGETHER_LLAMA_3_2_90B("together.llama-3.2-90b"),
  @SerializedName("together.llama-3.3-70b")
  TOGETHER_LLAMA_3_3_70B("together.llama-3.3-70b"),
  @SerializedName("together.deepseek-v3")
  TOGETHER_DEEPSEEK_V3("together.deepseek-v3"),
  @SerializedName("together.deepseek-r1")
  TOGETHER_DEEPSEEK_R1("together.deepseek-r1"),
  @SerializedName("together.deepseek-r1-distill-llama-70b")
  TOGETHER_DEEPSEEK_R1_DISTILL_LLAMA_70B("together.deepseek-r1-distill-llama-70b"),
  @SerializedName("together.deepseek-r1-distill-qwen-14b")
  TOGETHER_DEEPSEEK_R1_DISTILL_QWEN_14B("together.deepseek-r1-distill-qwen-14b"),
  @SerializedName("together.qwen-2")
  TOGETHER_QWEN_2("together.qwen-2"),
  @SerializedName("together.qwen-2.5-7b")
  TOGETHER_QWEN_2_5_7B("together.qwen-2.5-7b"),
  @SerializedName("together.qwen-2.5-72b")
  TOGETHER_QWEN_2_5_72B("together.qwen-2.5-72b"),
  @SerializedName("together.qwen-qwq")
  TOGETHER_QWEN_QWQ("together.qwen-qwq"),
  @SerializedName("together.qwen-coder-32b")
  TOGETHER_QWEN_CODER_32B("together.qwen-coder-32b"),
  @SerializedName("together.mistral-7b")
  TOGETHER_MISTRAL_7B("together.mistral-7b"),
  @SerializedName("vertex-ai.gemini-2.0-pro")
  VERTEX_AI_GEMINI_2_0_PRO("vertex-ai.gemini-2.0-pro"),
  @SerializedName("vertex-ai.gemini-2.0-flash")
  VERTEX_AI_GEMINI_2_0_FLASH("vertex-ai.gemini-2.0-flash"),
  @SerializedName("vertex-ai.claude-3.7-sonnet")
  VERTEX_AI_CLAUDE_3_7_SONNET("vertex-ai.claude-3.7-sonnet"),
  @SerializedName("vertex-ai.claude-3.5-sonnet")
  VERTEX_AI_CLAUDE_3_5_SONNET("vertex-ai.claude-3.5-sonnet"),
  @SerializedName("vertex-ai.claude-3.5-haiku")
  VERTEX_AI_CLAUDE_3_5_HAIKU("vertex-ai.claude-3.5-haiku");

  private Object value;

  LLMModelID(Object value) {
    this.value = value;
  }

  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LLMModelID fromValue(Object input) {
    for (LLMModelID b : LLMModelID.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<LLMModelID> {
    @Override
    public void write(final JsonWriter jsonWriter, final LLMModelID enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public LLMModelID read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return LLMModelID.fromValue((Object)(value));
    }
  }
}
