/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets QueryPipelineTraceEventType
 */
@JsonAdapter(QueryPipelineTraceEventType.Adapter.class)
public enum QueryPipelineTraceEventType {
  @SerializedName("memory_recall")
  MEMORY_RECALL("memory_recall"),
  @SerializedName("memory_save")
  MEMORY_SAVE("memory_save"),
  @SerializedName("agent_run")
  AGENT_RUN("agent_run"),
  @SerializedName("retrieval_run")
  RETRIEVAL_RUN("retrieval_run"),
  @SerializedName("completion_run")
  COMPLETION_RUN("completion_run");

  private Object value;

  QueryPipelineTraceEventType(Object value) {
    this.value = value;
  }

  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static QueryPipelineTraceEventType fromValue(Object input) {
    for (QueryPipelineTraceEventType b : QueryPipelineTraceEventType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<QueryPipelineTraceEventType> {
    @Override
    public void write(final JsonWriter jsonWriter, final QueryPipelineTraceEventType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public QueryPipelineTraceEventType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return QueryPipelineTraceEventType.fromValue((Object)(value));
    }
  }
}
