/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets QueryPipelineID
 */
@JsonAdapter(QueryPipelineID.Adapter.class)
public enum QueryPipelineID {
  @SerializedName("default_rag")
  DEFAULT_RAG("default_rag"),
  @SerializedName("document_summarization")
  DOCUMENT_SUMMARIZATION("document_summarization");

  private Object value;

  QueryPipelineID(Object value) {
    this.value = value;
  }

  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static QueryPipelineID fromValue(Object input) {
    for (QueryPipelineID b : QueryPipelineID.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<QueryPipelineID> {
    @Override
    public void write(final JsonWriter jsonWriter, final QueryPipelineID enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public QueryPipelineID read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return QueryPipelineID.fromValue((Object)(value));
    }
  }
}
