/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.QueryPipelineTraceEventType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * QueryPipelineTraceEvent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class QueryPipelineTraceEvent {
  @SerializedName("event_type")
  private QueryPipelineTraceEventType eventType = null;

  @SerializedName("event_inputs")
  private Object eventInputs = [];

  @SerializedName("event_outputs")
  private Object eventOutputs = [];

  @SerializedName("elapsed_time")
  private Object elapsedTime = 0;

  public QueryPipelineTraceEvent eventType(QueryPipelineTraceEventType eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * Event type.
   * @return eventType
  **/
  @Schema(required = true, description = "Event type.")
  public QueryPipelineTraceEventType getEventType() {
    return eventType;
  }

  public void setEventType(QueryPipelineTraceEventType eventType) {
    this.eventType = eventType;
  }

  public QueryPipelineTraceEvent eventInputs(Object eventInputs) {
    this.eventInputs = eventInputs;
    return this;
  }

   /**
   * Event inputs.
   * @return eventInputs
  **/
  @Schema(description = "Event inputs.")
  public Object getEventInputs() {
    return eventInputs;
  }

  public void setEventInputs(Object eventInputs) {
    this.eventInputs = eventInputs;
  }

  public QueryPipelineTraceEvent eventOutputs(Object eventOutputs) {
    this.eventOutputs = eventOutputs;
    return this;
  }

   /**
   * Event inputs.
   * @return eventOutputs
  **/
  @Schema(description = "Event inputs.")
  public Object getEventOutputs() {
    return eventOutputs;
  }

  public void setEventOutputs(Object eventOutputs) {
    this.eventOutputs = eventOutputs;
  }

  public QueryPipelineTraceEvent elapsedTime(Object elapsedTime) {
    this.elapsedTime = elapsedTime;
    return this;
  }

   /**
   * Pipeline event elapsed time.
   * @return elapsedTime
  **/
  @Schema(description = "Pipeline event elapsed time.")
  public Object getElapsedTime() {
    return elapsedTime;
  }

  public void setElapsedTime(Object elapsedTime) {
    this.elapsedTime = elapsedTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryPipelineTraceEvent queryPipelineTraceEvent = (QueryPipelineTraceEvent) o;
    return Objects.equals(this.eventType, queryPipelineTraceEvent.eventType) &&
        Objects.equals(this.eventInputs, queryPipelineTraceEvent.eventInputs) &&
        Objects.equals(this.eventOutputs, queryPipelineTraceEvent.eventOutputs) &&
        Objects.equals(this.elapsedTime, queryPipelineTraceEvent.elapsedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventType, eventInputs, eventOutputs, elapsedTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryPipelineTraceEvent {\n");
    
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    eventInputs: ").append(toIndentedString(eventInputs)).append("\n");
    sb.append("    eventOutputs: ").append(toIndentedString(eventOutputs)).append("\n");
    sb.append("    elapsedTime: ").append(toIndentedString(elapsedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
