/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RAGFactualityMode
 */
@JsonAdapter(RAGFactualityMode.Adapter.class)
public enum RAGFactualityMode {
  @SerializedName("grounded")
  GROUNDED("grounded"),
  @SerializedName("mixed")
  MIXED("mixed");

  private Object value;

  RAGFactualityMode(Object value) {
    this.value = value;
  }

  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RAGFactualityMode fromValue(Object input) {
    for (RAGFactualityMode b : RAGFactualityMode.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<RAGFactualityMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final RAGFactualityMode enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public RAGFactualityMode read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return RAGFactualityMode.fromValue((Object)(value));
    }
  }
}
