/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ReferenceObjectType
 */
@JsonAdapter(ReferenceObjectType.Adapter.class)
public enum ReferenceObjectType {
  @SerializedName("file")
  FILE("file"),
  @SerializedName("website")
  WEBSITE("website"),
  @SerializedName("youtube")
  YOUTUBE("youtube");

  private Object value;

  ReferenceObjectType(Object value) {
    this.value = value;
  }

  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ReferenceObjectType fromValue(Object input) {
    for (ReferenceObjectType b : ReferenceObjectType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ReferenceObjectType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ReferenceObjectType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ReferenceObjectType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ReferenceObjectType.fromValue((Object)(value));
    }
  }
}
