/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ReferenceObjectStatus
 */
@JsonAdapter(ReferenceObjectStatus.Adapter.class)
public enum ReferenceObjectStatus {
  @SerializedName("queued")
  QUEUED("queued"),
  @SerializedName("processing")
  PROCESSING("processing"),
  @SerializedName("failed")
  FAILED("failed"),
  @SerializedName("processed")
  PROCESSED("processed");

  private Object value;

  ReferenceObjectStatus(Object value) {
    this.value = value;
  }

  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ReferenceObjectStatus fromValue(Object input) {
    for (ReferenceObjectStatus b : ReferenceObjectStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ReferenceObjectStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ReferenceObjectStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ReferenceObjectStatus read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ReferenceObjectStatus.fromValue((Object)(value));
    }
  }
}
