/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ReferenceObjectType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Reference object excerpt. Contains specific extracted text from the source reference object. It&#x27;s meant to be used in retrieval and search specifically - if you need additional details, retrieve the reference object.
 */
@Schema(description = "Reference object excerpt. Contains specific extracted text from the source reference object. It's meant to be used in retrieval and search specifically - if you need additional details, retrieve the reference object.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class ReferenceObjectExcerptDataModel {
  @SerializedName("reference_object_id")
  private Object referenceObjectId = null;

  @SerializedName("page_num")
  private Object pageNum = 0;

  @SerializedName("offset")
  private Object offset = 0;

  @SerializedName("source_id")
  private Object sourceId = null;

  @SerializedName("source_name")
  private Object sourceName = null;

  @SerializedName("source_url")
  private Object sourceUrl = null;

  @SerializedName("object_type")
  private ReferenceObjectType objectType = file;

  @SerializedName("content")
  private Object content = null;

  @SerializedName("score")
  private Object score = 0;

  public ReferenceObjectExcerptDataModel referenceObjectId(Object referenceObjectId) {
    this.referenceObjectId = referenceObjectId;
    return this;
  }

   /**
   * The UUID of the original reference object.
   * @return referenceObjectId
  **/
  @Schema(required = true, description = "The UUID of the original reference object.")
  public Object getReferenceObjectId() {
    return referenceObjectId;
  }

  public void setReferenceObjectId(Object referenceObjectId) {
    this.referenceObjectId = referenceObjectId;
  }

  public ReferenceObjectExcerptDataModel pageNum(Object pageNum) {
    this.pageNum = pageNum;
    return this;
  }

   /**
   * The page number this excerpt is found at, indexed from 0. Value of -1 means pages are not supported.         This is much less useful than the actual chunk index, but users are dumb so what can you do really...
   * @return pageNum
  **/
  @Schema(description = "The page number this excerpt is found at, indexed from 0. Value of -1 means pages are not supported.         This is much less useful than the actual chunk index, but users are dumb so what can you do really...")
  public Object getPageNum() {
    return pageNum;
  }

  public void setPageNum(Object pageNum) {
    this.pageNum = pageNum;
  }

  public ReferenceObjectExcerptDataModel offset(Object offset) {
    this.offset = offset;
    return this;
  }

   /**
   * The offset at which this excerpt starts.
   * @return offset
  **/
  @Schema(description = "The offset at which this excerpt starts.")
  public Object getOffset() {
    return offset;
  }

  public void setOffset(Object offset) {
    this.offset = offset;
  }

  public ReferenceObjectExcerptDataModel sourceId(Object sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * The original source ID for this reference object. This field is not used internally, you can set it to any value you want.
   * @return sourceId
  **/
  @Schema(description = "The original source ID for this reference object. This field is not used internally, you can set it to any value you want.")
  public Object getSourceId() {
    return sourceId;
  }

  public void setSourceId(Object sourceId) {
    this.sourceId = sourceId;
  }

  public ReferenceObjectExcerptDataModel sourceName(Object sourceName) {
    this.sourceName = sourceName;
    return this;
  }

   /**
   * The original source name for this reference object.
   * @return sourceName
  **/
  @Schema(description = "The original source name for this reference object.")
  public Object getSourceName() {
    return sourceName;
  }

  public void setSourceName(Object sourceName) {
    this.sourceName = sourceName;
  }

  public ReferenceObjectExcerptDataModel sourceUrl(Object sourceUrl) {
    this.sourceUrl = sourceUrl;
    return this;
  }

   /**
   * The original source URL for this reference object - if any.
   * @return sourceUrl
  **/
  @Schema(description = "The original source URL for this reference object - if any.")
  public Object getSourceUrl() {
    return sourceUrl;
  }

  public void setSourceUrl(Object sourceUrl) {
    this.sourceUrl = sourceUrl;
  }

  public ReferenceObjectExcerptDataModel objectType(ReferenceObjectType objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * The type of this reference object.
   * @return objectType
  **/
  @Schema(description = "The type of this reference object.")
  public ReferenceObjectType getObjectType() {
    return objectType;
  }

  public void setObjectType(ReferenceObjectType objectType) {
    this.objectType = objectType;
  }

  public ReferenceObjectExcerptDataModel content(Object content) {
    this.content = content;
    return this;
  }

   /**
   * The content of the reference object excerpt.
   * @return content
  **/
  @Schema(description = "The content of the reference object excerpt.")
  public Object getContent() {
    return content;
  }

  public void setContent(Object content) {
    this.content = content;
  }

  public ReferenceObjectExcerptDataModel score(Object score) {
    this.score = score;
    return this;
  }

   /**
   * The relevance score.
   * @return score
  **/
  @Schema(description = "The relevance score.")
  public Object getScore() {
    return score;
  }

  public void setScore(Object score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceObjectExcerptDataModel referenceObjectExcerptDataModel = (ReferenceObjectExcerptDataModel) o;
    return Objects.equals(this.referenceObjectId, referenceObjectExcerptDataModel.referenceObjectId) &&
        Objects.equals(this.pageNum, referenceObjectExcerptDataModel.pageNum) &&
        Objects.equals(this.offset, referenceObjectExcerptDataModel.offset) &&
        Objects.equals(this.sourceId, referenceObjectExcerptDataModel.sourceId) &&
        Objects.equals(this.sourceName, referenceObjectExcerptDataModel.sourceName) &&
        Objects.equals(this.sourceUrl, referenceObjectExcerptDataModel.sourceUrl) &&
        Objects.equals(this.objectType, referenceObjectExcerptDataModel.objectType) &&
        Objects.equals(this.content, referenceObjectExcerptDataModel.content) &&
        Objects.equals(this.score, referenceObjectExcerptDataModel.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceObjectId, pageNum, offset, sourceId, sourceName, sourceUrl, objectType, content, score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceObjectExcerptDataModel {\n");
    
    sb.append("    referenceObjectId: ").append(toIndentedString(referenceObjectId)).append("\n");
    sb.append("    pageNum: ").append(toIndentedString(pageNum)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    sourceName: ").append(toIndentedString(sourceName)).append("\n");
    sb.append("    sourceUrl: ").append(toIndentedString(sourceUrl)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
