/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateApplicationRequestModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class UpdateApplicationRequestModel {
  @SerializedName("name")
  private Object name = null;

  @SerializedName("organization_id")
  private Object organizationId = null;

  @SerializedName("api_calls_limit_per_month")
  private Object apiCallsLimitPerMonth = 0;

  @SerializedName("llm_tokens_limit_per_month")
  private Object llmTokensLimitPerMonth = 0;

  @SerializedName("embedding_tokens_limit_per_month")
  private Object embeddingTokensLimitPerMonth = 0;

  @SerializedName("image_generation_limit_per_month")
  private Object imageGenerationLimitPerMonth = 0;

  @SerializedName("allow_llm_queries")
  private Object allowLlmQueries = true;

  @SerializedName("allow_corpus_creation")
  private Object allowCorpusCreation = true;

  @SerializedName("allow_image_generation")
  private Object allowImageGeneration = true;

  @SerializedName("allow_expensive_queries")
  private Object allowExpensiveQueries = true;

  @SerializedName("webhook_url")
  private Object webhookUrl = null;

  @SerializedName("is_active")
  private Object isActive = true;

  public UpdateApplicationRequestModel name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of this application.
   * @return name
  **/
  @Schema(required = true, description = "The name of this application.")
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public UpdateApplicationRequestModel organizationId(Object organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * The UUID of the organization behind this application.
   * @return organizationId
  **/
  @Schema(required = true, description = "The UUID of the organization behind this application.")
  public Object getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Object organizationId) {
    this.organizationId = organizationId;
  }

  public UpdateApplicationRequestModel apiCallsLimitPerMonth(Object apiCallsLimitPerMonth) {
    this.apiCallsLimitPerMonth = apiCallsLimitPerMonth;
    return this;
  }

   /**
   * The maximum amount of API calls this application can make in a month.
   * @return apiCallsLimitPerMonth
  **/
  @Schema(description = "The maximum amount of API calls this application can make in a month.")
  public Object getApiCallsLimitPerMonth() {
    return apiCallsLimitPerMonth;
  }

  public void setApiCallsLimitPerMonth(Object apiCallsLimitPerMonth) {
    this.apiCallsLimitPerMonth = apiCallsLimitPerMonth;
  }

  public UpdateApplicationRequestModel llmTokensLimitPerMonth(Object llmTokensLimitPerMonth) {
    this.llmTokensLimitPerMonth = llmTokensLimitPerMonth;
    return this;
  }

   /**
   * The maximum amount of LLM tokens (combined I/O) this application can use in a month.
   * @return llmTokensLimitPerMonth
  **/
  @Schema(description = "The maximum amount of LLM tokens (combined I/O) this application can use in a month.")
  public Object getLlmTokensLimitPerMonth() {
    return llmTokensLimitPerMonth;
  }

  public void setLlmTokensLimitPerMonth(Object llmTokensLimitPerMonth) {
    this.llmTokensLimitPerMonth = llmTokensLimitPerMonth;
  }

  public UpdateApplicationRequestModel embeddingTokensLimitPerMonth(Object embeddingTokensLimitPerMonth) {
    this.embeddingTokensLimitPerMonth = embeddingTokensLimitPerMonth;
    return this;
  }

   /**
   * The maximum amount of embedding tokens this application can use in a month.
   * @return embeddingTokensLimitPerMonth
  **/
  @Schema(description = "The maximum amount of embedding tokens this application can use in a month.")
  public Object getEmbeddingTokensLimitPerMonth() {
    return embeddingTokensLimitPerMonth;
  }

  public void setEmbeddingTokensLimitPerMonth(Object embeddingTokensLimitPerMonth) {
    this.embeddingTokensLimitPerMonth = embeddingTokensLimitPerMonth;
  }

  public UpdateApplicationRequestModel imageGenerationLimitPerMonth(Object imageGenerationLimitPerMonth) {
    this.imageGenerationLimitPerMonth = imageGenerationLimitPerMonth;
    return this;
  }

   /**
   * The maximum amount of images this application can generate in a month.
   * @return imageGenerationLimitPerMonth
  **/
  @Schema(description = "The maximum amount of images this application can generate in a month.")
  public Object getImageGenerationLimitPerMonth() {
    return imageGenerationLimitPerMonth;
  }

  public void setImageGenerationLimitPerMonth(Object imageGenerationLimitPerMonth) {
    this.imageGenerationLimitPerMonth = imageGenerationLimitPerMonth;
  }

  public UpdateApplicationRequestModel allowLlmQueries(Object allowLlmQueries) {
    this.allowLlmQueries = allowLlmQueries;
    return this;
  }

   /**
   * Should this application be allowed to make queries to LLMs?
   * @return allowLlmQueries
  **/
  @Schema(description = "Should this application be allowed to make queries to LLMs?")
  public Object getAllowLlmQueries() {
    return allowLlmQueries;
  }

  public void setAllowLlmQueries(Object allowLlmQueries) {
    this.allowLlmQueries = allowLlmQueries;
  }

  public UpdateApplicationRequestModel allowCorpusCreation(Object allowCorpusCreation) {
    this.allowCorpusCreation = allowCorpusCreation;
    return this;
  }

   /**
   * Should this application be allowed to create corpuses?
   * @return allowCorpusCreation
  **/
  @Schema(description = "Should this application be allowed to create corpuses?")
  public Object getAllowCorpusCreation() {
    return allowCorpusCreation;
  }

  public void setAllowCorpusCreation(Object allowCorpusCreation) {
    this.allowCorpusCreation = allowCorpusCreation;
  }

  public UpdateApplicationRequestModel allowImageGeneration(Object allowImageGeneration) {
    this.allowImageGeneration = allowImageGeneration;
    return this;
  }

   /**
   * Should this application be allowed to create images?
   * @return allowImageGeneration
  **/
  @Schema(description = "Should this application be allowed to create images?")
  public Object getAllowImageGeneration() {
    return allowImageGeneration;
  }

  public void setAllowImageGeneration(Object allowImageGeneration) {
    this.allowImageGeneration = allowImageGeneration;
  }

  public UpdateApplicationRequestModel allowExpensiveQueries(Object allowExpensiveQueries) {
    this.allowExpensiveQueries = allowExpensiveQueries;
    return this;
  }

   /**
   * Should this application be allowed to make potentially expensive queries?
   * @return allowExpensiveQueries
  **/
  @Schema(description = "Should this application be allowed to make potentially expensive queries?")
  public Object getAllowExpensiveQueries() {
    return allowExpensiveQueries;
  }

  public void setAllowExpensiveQueries(Object allowExpensiveQueries) {
    this.allowExpensiveQueries = allowExpensiveQueries;
  }

  public UpdateApplicationRequestModel webhookUrl(Object webhookUrl) {
    this.webhookUrl = webhookUrl;
    return this;
  }

   /**
   * Webhook URL to use when notifying of queued events.
   * @return webhookUrl
  **/
  @Schema(description = "Webhook URL to use when notifying of queued events.")
  public Object getWebhookUrl() {
    return webhookUrl;
  }

  public void setWebhookUrl(Object webhookUrl) {
    this.webhookUrl = webhookUrl;
  }

  public UpdateApplicationRequestModel isActive(Object isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Is this application active?
   * @return isActive
  **/
  @Schema(description = "Is this application active?")
  public Object getIsActive() {
    return isActive;
  }

  public void setIsActive(Object isActive) {
    this.isActive = isActive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApplicationRequestModel updateApplicationRequestModel = (UpdateApplicationRequestModel) o;
    return Objects.equals(this.name, updateApplicationRequestModel.name) &&
        Objects.equals(this.organizationId, updateApplicationRequestModel.organizationId) &&
        Objects.equals(this.apiCallsLimitPerMonth, updateApplicationRequestModel.apiCallsLimitPerMonth) &&
        Objects.equals(this.llmTokensLimitPerMonth, updateApplicationRequestModel.llmTokensLimitPerMonth) &&
        Objects.equals(this.embeddingTokensLimitPerMonth, updateApplicationRequestModel.embeddingTokensLimitPerMonth) &&
        Objects.equals(this.imageGenerationLimitPerMonth, updateApplicationRequestModel.imageGenerationLimitPerMonth) &&
        Objects.equals(this.allowLlmQueries, updateApplicationRequestModel.allowLlmQueries) &&
        Objects.equals(this.allowCorpusCreation, updateApplicationRequestModel.allowCorpusCreation) &&
        Objects.equals(this.allowImageGeneration, updateApplicationRequestModel.allowImageGeneration) &&
        Objects.equals(this.allowExpensiveQueries, updateApplicationRequestModel.allowExpensiveQueries) &&
        Objects.equals(this.webhookUrl, updateApplicationRequestModel.webhookUrl) &&
        Objects.equals(this.isActive, updateApplicationRequestModel.isActive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, organizationId, apiCallsLimitPerMonth, llmTokensLimitPerMonth, embeddingTokensLimitPerMonth, imageGenerationLimitPerMonth, allowLlmQueries, allowCorpusCreation, allowImageGeneration, allowExpensiveQueries, webhookUrl, isActive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApplicationRequestModel {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    apiCallsLimitPerMonth: ").append(toIndentedString(apiCallsLimitPerMonth)).append("\n");
    sb.append("    llmTokensLimitPerMonth: ").append(toIndentedString(llmTokensLimitPerMonth)).append("\n");
    sb.append("    embeddingTokensLimitPerMonth: ").append(toIndentedString(embeddingTokensLimitPerMonth)).append("\n");
    sb.append("    imageGenerationLimitPerMonth: ").append(toIndentedString(imageGenerationLimitPerMonth)).append("\n");
    sb.append("    allowLlmQueries: ").append(toIndentedString(allowLlmQueries)).append("\n");
    sb.append("    allowCorpusCreation: ").append(toIndentedString(allowCorpusCreation)).append("\n");
    sb.append("    allowImageGeneration: ").append(toIndentedString(allowImageGeneration)).append("\n");
    sb.append("    allowExpensiveQueries: ").append(toIndentedString(allowExpensiveQueries)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
