/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OrganizationDataModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateOrganizationResponseModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-06T03:00:29.225012130Z[GMT]")

public class UpdateOrganizationResponseModel {
  @SerializedName("organization")
  private OrganizationDataModel organization = null;

  public UpdateOrganizationResponseModel organization(OrganizationDataModel organization) {
    this.organization = organization;
    return this;
  }

   /**
   * The organization that was updated in this request.
   * @return organization
  **/
  @Schema(required = true, description = "The organization that was updated in this request.")
  public OrganizationDataModel getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationDataModel organization) {
    this.organization = organization;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateOrganizationResponseModel updateOrganizationResponseModel = (UpdateOrganizationResponseModel) o;
    return Objects.equals(this.organization, updateOrganizationResponseModel.organization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organization);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateOrganizationResponseModel {\n");
    
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
