/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateConversationMessageRequestModel;
import io.swagger.client.model.CreateConversationMessageResponseModel;
import io.swagger.client.model.CreateConversationRequestModel;
import io.swagger.client.model.CreateConversationResponseModel;
import io.swagger.client.model.DeleteConversationResponseModel;
import io.swagger.client.model.GetConversationResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.ListConversationMessagesResponseModel;
import io.swagger.client.model.ListConversationsResponseModel;
import io.swagger.client.model.UpdateConversationRequestModel;
import io.swagger.client.model.UpdateConversationResponseModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ChatbotconversationsApi
 */
@Ignore
public class ChatbotconversationsApiTest {

    private final ChatbotconversationsApi api = new ChatbotconversationsApi();

    /**
     * Create A Conversation
     *
     * Creates a conversation.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createAConversationV3ChatbotConversationsPostTest() throws Exception {
        CreateConversationRequestModel body = null;
        CreateConversationResponseModel response = api.createAConversationV3ChatbotConversationsPost(body);

        // TODO: test validations
    }
    /**
     * Create A New Message In A Conversation
     *
     * Creates a new message in a conversation along with a completion from the LLM.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostTest() throws Exception {
        CreateConversationMessageRequestModel body = null;
        Object conversationId = null;
        CreateConversationMessageResponseModel response = api.createANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost(body, conversationId);

        // TODO: test validations
    }
    /**
     * Delete A Conversation
     *
     * Deletes the conversation specified in &#x60;conversation_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAConversationV3ChatbotConversationsConversationIdDeleteTest() throws Exception {
        Object conversationId = null;
        DeleteConversationResponseModel response = api.deleteAConversationV3ChatbotConversationsConversationIdDelete(conversationId);

        // TODO: test validations
    }
    /**
     * Get A Conversation
     *
     * Returns a conversation matching the provided &#x60;conversation_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAConversationV3ChatbotConversationsConversationIdGetTest() throws Exception {
        Object conversationId = null;
        GetConversationResponseModel response = api.getAConversationV3ChatbotConversationsConversationIdGet(conversationId);

        // TODO: test validations
    }
    /**
     * List All Conversations
     *
     * Lists all conversations.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAllConversationsV3ChatbotConversationsGetTest() throws Exception {
        ListConversationsResponseModel response = api.listAllConversationsV3ChatbotConversationsGet();

        // TODO: test validations
    }
    /**
     * List Conversation Messages
     *
     * Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listConversationMessagesV3ChatbotConversationsConversationIdMessagesGetTest() throws Exception {
        Object conversationId = null;
        ListConversationMessagesResponseModel response = api.listConversationMessagesV3ChatbotConversationsConversationIdMessagesGet(conversationId);

        // TODO: test validations
    }
    /**
     * Update A Conversation
     *
     * Updates the conversation specified in &#x60;conversation_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateAConversationV3ChatbotConversationsConversationIdPatchTest() throws Exception {
        UpdateConversationRequestModel body = null;
        Object conversationId = null;
        UpdateConversationResponseModel response = api.updateAConversationV3ChatbotConversationsConversationIdPatch(body, conversationId);

        // TODO: test validations
    }
}
