/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateApplicationRequestModel;
import io.swagger.client.model.CreateApplicationResponseModel;
import io.swagger.client.model.DeleteApplicationResponseModel;
import io.swagger.client.model.GetApplicationResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.ListApplicationsResponseModel;
import io.swagger.client.model.UpdateApplicationRequestModel;
import io.swagger.client.model.UpdateApplicationResponseModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ManagementapplicationsApi
 */
@Ignore
public class ManagementapplicationsApiTest {

    private final ManagementapplicationsApi api = new ManagementapplicationsApi();

    /**
     * Create An Application
     *
     * Creates an application.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createAnApplicationV3ManagementApplicationsPostTest() throws Exception {
        CreateApplicationRequestModel body = null;
        CreateApplicationResponseModel response = api.createAnApplicationV3ManagementApplicationsPost(body);

        // TODO: test validations
    }
    /**
     * Delete An Application
     *
     * Deletes the application specified in &#x60;application_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAnApplicationV3ManagementApplicationsApplicationIdDeleteTest() throws Exception {
        Object applicationId = null;
        DeleteApplicationResponseModel response = api.deleteAnApplicationV3ManagementApplicationsApplicationIdDelete(applicationId);

        // TODO: test validations
    }
    /**
     * Get An Application
     *
     * Returns an application matching the provided &#x60;application_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAnApplicationV3ManagementApplicationsApplicationIdGetTest() throws Exception {
        Object applicationId = null;
        GetApplicationResponseModel response = api.getAnApplicationV3ManagementApplicationsApplicationIdGet(applicationId);

        // TODO: test validations
    }
    /**
     * List All Applications
     *
     * Lists all applications.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAllApplicationsV3ManagementApplicationsGetTest() throws Exception {
        ListApplicationsResponseModel response = api.listAllApplicationsV3ManagementApplicationsGet();

        // TODO: test validations
    }
    /**
     * Update An Application
     *
     * Updates the application specified in &#x60;application_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateAnApplicationV3ManagementApplicationsApplicationIdPatchTest() throws Exception {
        UpdateApplicationRequestModel body = null;
        Object applicationId = null;
        UpdateApplicationResponseModel response = api.updateAnApplicationV3ManagementApplicationsApplicationIdPatch(body, applicationId);

        // TODO: test validations
    }
}
