/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateOrganizationRequestModel;
import io.swagger.client.model.CreateOrganizationResponseModel;
import io.swagger.client.model.DeleteOrganizationResponseModel;
import io.swagger.client.model.GetOrganizationResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.ListOrganizationApplicationsResponseModel;
import io.swagger.client.model.ListOrganizationsResponseModel;
import io.swagger.client.model.UpdateOrganizationRequestModel;
import io.swagger.client.model.UpdateOrganizationResponseModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ManagementorganizationsApi
 */
@Ignore
public class ManagementorganizationsApiTest {

    private final ManagementorganizationsApi api = new ManagementorganizationsApi();

    /**
     * Create An Organization
     *
     * Creates an organization.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createAnOrganizationV3ManagementOrganizationsPostTest() throws Exception {
        CreateOrganizationRequestModel body = null;
        CreateOrganizationResponseModel response = api.createAnOrganizationV3ManagementOrganizationsPost(body);

        // TODO: test validations
    }
    /**
     * Delete An Organization
     *
     * Deletes the organization specified in &#x60;organization_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAnOrganizationV3ManagementOrganizationsOrganizationIdDeleteTest() throws Exception {
        Object organizationId = null;
        DeleteOrganizationResponseModel response = api.deleteAnOrganizationV3ManagementOrganizationsOrganizationIdDelete(organizationId);

        // TODO: test validations
    }
    /**
     * Get An Organization
     *
     * Returns an organization matching the provided &#x60;organization_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAnOrganizationV3ManagementOrganizationsOrganizationIdGetTest() throws Exception {
        Object organizationId = null;
        GetOrganizationResponseModel response = api.getAnOrganizationV3ManagementOrganizationsOrganizationIdGet(organizationId);

        // TODO: test validations
    }
    /**
     * List All Organizations
     *
     * Lists all organizations.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAllOrganizationsV3ManagementOrganizationsGetTest() throws Exception {
        ListOrganizationsResponseModel response = api.listAllOrganizationsV3ManagementOrganizationsGet();

        // TODO: test validations
    }
    /**
     * List Organization Applications
     *
     * Lists all applications associated with an organization specified in &#x60;organization_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listOrganizationApplicationsV3ManagementOrganizationsOrganizationIdApplicationsGetTest() throws Exception {
        Object organizationId = null;
        ListOrganizationApplicationsResponseModel response = api.listOrganizationApplicationsV3ManagementOrganizationsOrganizationIdApplicationsGet(organizationId);

        // TODO: test validations
    }
    /**
     * Update An Organization
     *
     * Updates the organization specified in &#x60;organization_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateAnOrganizationV3ManagementOrganizationsOrganizationIdPatchTest() throws Exception {
        UpdateOrganizationRequestModel body = null;
        Object organizationId = null;
        UpdateOrganizationResponseModel response = api.updateAnOrganizationV3ManagementOrganizationsOrganizationIdPatch(body, organizationId);

        // TODO: test validations
    }
}
