/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateLLMCompletionRequestModel;
import io.swagger.client.model.CreateLLMCompletionResponseModel;
import io.swagger.client.model.EmbeddingInferenceProviderID;
import io.swagger.client.model.GetLLMModelResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.LLMInferenceProviderID;
import io.swagger.client.model.LLMModelID;
import io.swagger.client.model.ListEmbeddingInferenceProviderModelsResponseModel;
import io.swagger.client.model.ListEmbeddingInferenceProvidersResponseModel;
import io.swagger.client.model.ListLLMInferenceProviderModelsResponseModel;
import io.swagger.client.model.ListLLMInferenceProvidersResponseModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ModelsApi
 */
@Ignore
public class ModelsApiTest {

    private final ModelsApi api = new ModelsApi();

    /**
     * Create A Completion
     *
     * Creates an LLM completion.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostTest() throws Exception {
        CreateLLMCompletionRequestModel body = null;
        LLMInferenceProviderID llmInferenceProviderId = null;
        LLMModelID llmModelId = null;
        CreateLLMCompletionResponseModel response = api.createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost(body, llmInferenceProviderId, llmModelId);

        // TODO: test validations
    }
    /**
     * Create A Streaming Completion
     *
     * Creates a streaming LLM completion.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostTest() throws Exception {
        CreateLLMCompletionRequestModel body = null;
        LLMInferenceProviderID llmInferenceProviderId = null;
        LLMModelID llmModelId = null;
        Object response = api.createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost(body, llmInferenceProviderId, llmModelId);

        // TODO: test validations
    }
    /**
     * Get Model Information
     *
     * Gets information for a specified model.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetTest() throws Exception {
        LLMInferenceProviderID llmInferenceProviderId = null;
        LLMModelID llmModelId = null;
        GetLLMModelResponseModel response = api.getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet(llmInferenceProviderId, llmModelId);

        // TODO: test validations
    }
    /**
     * List All Embedding Inference Providers
     *
     * List all embedding inference providers.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetTest() throws Exception {
        ListEmbeddingInferenceProvidersResponseModel response = api.listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGet();

        // TODO: test validations
    }
    /**
     * List All Llm Inference Providers
     *
     * List all LLM inference providers.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetTest() throws Exception {
        ListLLMInferenceProvidersResponseModel response = api.listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet();

        // TODO: test validations
    }
    /**
     * List Embedding Inference Provider Models
     *
     * Lists all embedding models in the provided embedding inference provider.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetTest() throws Exception {
        EmbeddingInferenceProviderID embeddingInferenceProviderId = null;
        ListEmbeddingInferenceProviderModelsResponseModel response = api.listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGet(embeddingInferenceProviderId);

        // TODO: test validations
    }
    /**
     * List Llm Inference Provider Models
     *
     * Lists all LLM models in the provided llm inference provider.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetTest() throws Exception {
        LLMInferenceProviderID llmInferenceProviderId = null;
        ListLLMInferenceProviderModelsResponseModel response = api.listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet(llmInferenceProviderId);

        // TODO: test validations
    }
}
