/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateCorpusRequestModel;
import io.swagger.client.model.CreateCorpusResponseModel;
import io.swagger.client.model.DeleteCorpusResponseModel;
import io.swagger.client.model.GetCorpusResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.ListCorporaResponseModel;
import io.swagger.client.model.ListCorpusReferenceObjectsResponseModel;
import io.swagger.client.model.UpdateCorpusRequestModel;
import io.swagger.client.model.UpdateCorpusResponseModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RagcorporaApi
 */
@Ignore
public class RagcorporaApiTest {

    private final RagcorporaApi api = new RagcorporaApi();

    /**
     * Create A Corpus
     *
     * Creates a corpus.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createACorpusV3RagCorporaPostTest() throws Exception {
        CreateCorpusRequestModel body = null;
        CreateCorpusResponseModel response = api.createACorpusV3RagCorporaPost(body);

        // TODO: test validations
    }
    /**
     * Delete A Corpus
     *
     * Deletes the corpus specified in &#x60;corpus_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteACorpusV3RagCorporaCorpusIdDeleteTest() throws Exception {
        Object corpusId = null;
        DeleteCorpusResponseModel response = api.deleteACorpusV3RagCorporaCorpusIdDelete(corpusId);

        // TODO: test validations
    }
    /**
     * Get A Corpus
     *
     * Returns a corpus matching the provided &#x60;corpus_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getACorpusV3RagCorporaCorpusIdGetTest() throws Exception {
        Object corpusId = null;
        GetCorpusResponseModel response = api.getACorpusV3RagCorporaCorpusIdGet(corpusId);

        // TODO: test validations
    }
    /**
     * List All Corpora
     *
     * Lists all corpora.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAllCorporaV3RagCorporaGetTest() throws Exception {
        ListCorporaResponseModel response = api.listAllCorporaV3RagCorporaGet();

        // TODO: test validations
    }
    /**
     * List Corpus Reference Objects
     *
     * Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetTest() throws Exception {
        Object corpusId = null;
        ListCorpusReferenceObjectsResponseModel response = api.listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet(corpusId);

        // TODO: test validations
    }
    /**
     * Update A Corpus
     *
     * Updates the corpus specified in &#x60;corpus_id&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateACorpusV3RagCorporaCorpusIdPatchTest() throws Exception {
        UpdateCorpusRequestModel body = null;
        Object corpusId = null;
        UpdateCorpusResponseModel response = api.updateACorpusV3RagCorporaCorpusIdPatch(body, corpusId);

        // TODO: test validations
    }
}
