/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateReferenceObjectSearchRequestModel;
import io.swagger.client.model.CreateReferenceObjectSearchResponseModel;
import io.swagger.client.model.HTTPValidationError;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RagsearchesApi
 */
@Ignore
public class RagsearchesApiTest {

    private final RagsearchesApi api = new RagsearchesApi();

    /**
     * Create A Reference Object Search
     *
     * Creates a reference object search query and returns results.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createAReferenceObjectSearchV3RagSearchesReferenceObjectsPostTest() throws Exception {
        CreateReferenceObjectSearchRequestModel body = null;
        Object corpusId = null;
        CreateReferenceObjectSearchResponseModel response = api.createAReferenceObjectSearchV3RagSearchesReferenceObjectsPost(body, corpusId);

        // TODO: test validations
    }
}
