/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.EmbeddingInferenceProviderID;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.ListEmbeddingInferenceProviderModelsResponseModel;
import io.swagger.client.model.ListEmbeddingInferenceProvidersResponseModel;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ModelsembeddingsApi {
    private ApiClient apiClient;
    private Map<String, String> headers;

    public ModelsembeddingsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ModelsembeddingsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public void setHeadersOverrides(Map<String, String> headers) {
        this.headers = headers;
    }

    /**
     * Build call for listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/models/embeddings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List All Embedding Inference Providers
     * List all embedding inference providers.
     * @return ListEmbeddingInferenceProvidersResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListEmbeddingInferenceProvidersResponseModel listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGet() throws ApiException {
        ApiResponse<ListEmbeddingInferenceProvidersResponseModel> resp = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * List All Embedding Inference Providers
     * List all embedding inference providers.
     * @return ApiResponse&lt;ListEmbeddingInferenceProvidersResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListEmbeddingInferenceProvidersResponseModel> listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProvidersResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List All Embedding Inference Providers (asynchronously)
     * List all embedding inference providers.
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetAsync(final ApiCallback<ListEmbeddingInferenceProvidersResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProvidersResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGet
     * @param embeddingInferenceProviderId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetCall(EmbeddingInferenceProviderID embeddingInferenceProviderId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/models/embeddings/{embedding_inference_provider_id}"
            .replaceAll("\\{" + "embedding_inference_provider_id" + "\\}", apiClient.escapeString(embeddingInferenceProviderId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetValidateBeforeCall(EmbeddingInferenceProviderID embeddingInferenceProviderId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'embeddingInferenceProviderId' is set
        if (embeddingInferenceProviderId == null) {
            throw new ApiException("Missing the required parameter 'embeddingInferenceProviderId' when calling listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGet(Async)");
        }
        
        com.squareup.okhttp.Call call = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetCall(embeddingInferenceProviderId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List Embedding Inference Provider Models
     * Lists all embedding models in the provided embedding inference provider.
     * @param embeddingInferenceProviderId  (required)
     * @return ListEmbeddingInferenceProviderModelsResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListEmbeddingInferenceProviderModelsResponseModel listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGet(EmbeddingInferenceProviderID embeddingInferenceProviderId) throws ApiException {
        ApiResponse<ListEmbeddingInferenceProviderModelsResponseModel> resp = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetWithHttpInfo(embeddingInferenceProviderId);
        return resp.getData();
    }

    /**
     * List Embedding Inference Provider Models
     * Lists all embedding models in the provided embedding inference provider.
     * @param embeddingInferenceProviderId  (required)
     * @return ApiResponse&lt;ListEmbeddingInferenceProviderModelsResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListEmbeddingInferenceProviderModelsResponseModel> listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetWithHttpInfo(EmbeddingInferenceProviderID embeddingInferenceProviderId) throws ApiException {
        com.squareup.okhttp.Call call = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetValidateBeforeCall(embeddingInferenceProviderId, null, null);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProviderModelsResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List Embedding Inference Provider Models (asynchronously)
     * Lists all embedding models in the provided embedding inference provider.
     * @param embeddingInferenceProviderId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetAsync(EmbeddingInferenceProviderID embeddingInferenceProviderId, final ApiCallback<ListEmbeddingInferenceProviderModelsResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetValidateBeforeCall(embeddingInferenceProviderId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProviderModelsResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
