/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.CreateLLMCompletionRequestModel;
import io.swagger.client.model.CreateLLMCompletionResponseModel;
import io.swagger.client.model.EmbeddingInferenceProviderID;
import io.swagger.client.model.GetLLMModelResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.LLMInferenceProviderID;
import io.swagger.client.model.LLMModelID;
import io.swagger.client.model.ListEmbeddingInferenceProviderModelsResponseModel;
import io.swagger.client.model.ListEmbeddingInferenceProvidersResponseModel;
import io.swagger.client.model.ListLLMInferenceProviderModelsResponseModel;
import io.swagger.client.model.ListLLMInferenceProvidersResponseModel;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ModelsApi {
    private ApiClient apiClient;
    private Map<String, String> headers;

    public ModelsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ModelsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public void setHeadersOverrides(Map<String, String> headers) {
        this.headers = headers;
    }

    /**
     * Build call for createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostCall(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}"
            .replaceAll("\\{" + "llm_inference_provider_id" + "\\}", apiClient.escapeString(llmInferenceProviderId.toString()))
            .replaceAll("\\{" + "llm_model_id" + "\\}", apiClient.escapeString(llmModelId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostValidateBeforeCall(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost(Async)");
        }
        // verify the required parameter 'llmInferenceProviderId' is set
        if (llmInferenceProviderId == null) {
            throw new ApiException("Missing the required parameter 'llmInferenceProviderId' when calling createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost(Async)");
        }
        // verify the required parameter 'llmModelId' is set
        if (llmModelId == null) {
            throw new ApiException("Missing the required parameter 'llmModelId' when calling createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost(Async)");
        }
        
        com.squareup.okhttp.Call call = createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostCall(body, llmInferenceProviderId, llmModelId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Create A Completion
     * Creates an LLM completion.
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @return CreateLLMCompletionResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreateLLMCompletionResponseModel createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId) throws ApiException {
        ApiResponse<CreateLLMCompletionResponseModel> resp = createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostWithHttpInfo(body, llmInferenceProviderId, llmModelId);
        return resp.getData();
    }

    /**
     * Create A Completion
     * Creates an LLM completion.
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @return ApiResponse&lt;CreateLLMCompletionResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreateLLMCompletionResponseModel> createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostWithHttpInfo(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId) throws ApiException {
        com.squareup.okhttp.Call call = createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostValidateBeforeCall(body, llmInferenceProviderId, llmModelId, null, null);
        Type localVarReturnType = new TypeToken<CreateLLMCompletionResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Create A Completion (asynchronously)
     * Creates an LLM completion.
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostAsync(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ApiCallback<CreateLLMCompletionResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostValidateBeforeCall(body, llmInferenceProviderId, llmModelId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreateLLMCompletionResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostCall(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}/stream"
            .replaceAll("\\{" + "llm_inference_provider_id" + "\\}", apiClient.escapeString(llmInferenceProviderId.toString()))
            .replaceAll("\\{" + "llm_model_id" + "\\}", apiClient.escapeString(llmModelId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostValidateBeforeCall(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost(Async)");
        }
        // verify the required parameter 'llmInferenceProviderId' is set
        if (llmInferenceProviderId == null) {
            throw new ApiException("Missing the required parameter 'llmInferenceProviderId' when calling createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost(Async)");
        }
        // verify the required parameter 'llmModelId' is set
        if (llmModelId == null) {
            throw new ApiException("Missing the required parameter 'llmModelId' when calling createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost(Async)");
        }
        
        com.squareup.okhttp.Call call = createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostCall(body, llmInferenceProviderId, llmModelId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Create A Streaming Completion
     * Creates a streaming LLM completion.
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Object createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId) throws ApiException {
        ApiResponse<Object> resp = createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostWithHttpInfo(body, llmInferenceProviderId, llmModelId);
        return resp.getData();
    }

    /**
     * Create A Streaming Completion
     * Creates a streaming LLM completion.
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Object> createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostWithHttpInfo(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId) throws ApiException {
        com.squareup.okhttp.Call call = createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostValidateBeforeCall(body, llmInferenceProviderId, llmModelId, null, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Create A Streaming Completion (asynchronously)
     * Creates a streaming LLM completion.
     * @param body  (required)
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostAsync(CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ApiCallback<Object> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostValidateBeforeCall(body, llmInferenceProviderId, llmModelId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetCall(LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}"
            .replaceAll("\\{" + "llm_inference_provider_id" + "\\}", apiClient.escapeString(llmInferenceProviderId.toString()))
            .replaceAll("\\{" + "llm_model_id" + "\\}", apiClient.escapeString(llmModelId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetValidateBeforeCall(LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'llmInferenceProviderId' is set
        if (llmInferenceProviderId == null) {
            throw new ApiException("Missing the required parameter 'llmInferenceProviderId' when calling getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet(Async)");
        }
        // verify the required parameter 'llmModelId' is set
        if (llmModelId == null) {
            throw new ApiException("Missing the required parameter 'llmModelId' when calling getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet(Async)");
        }
        
        com.squareup.okhttp.Call call = getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetCall(llmInferenceProviderId, llmModelId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get Model Information
     * Gets information for a specified model.
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @return GetLLMModelResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public GetLLMModelResponseModel getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet(LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId) throws ApiException {
        ApiResponse<GetLLMModelResponseModel> resp = getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetWithHttpInfo(llmInferenceProviderId, llmModelId);
        return resp.getData();
    }

    /**
     * Get Model Information
     * Gets information for a specified model.
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @return ApiResponse&lt;GetLLMModelResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<GetLLMModelResponseModel> getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetWithHttpInfo(LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId) throws ApiException {
        com.squareup.okhttp.Call call = getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetValidateBeforeCall(llmInferenceProviderId, llmModelId, null, null);
        Type localVarReturnType = new TypeToken<GetLLMModelResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get Model Information (asynchronously)
     * Gets information for a specified model.
     * @param llmInferenceProviderId  (required)
     * @param llmModelId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetAsync(LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId, final ApiCallback<GetLLMModelResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetValidateBeforeCall(llmInferenceProviderId, llmModelId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<GetLLMModelResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/models/embeddings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List All Embedding Inference Providers
     * List all embedding inference providers.
     * @return ListEmbeddingInferenceProvidersResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListEmbeddingInferenceProvidersResponseModel listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGet() throws ApiException {
        ApiResponse<ListEmbeddingInferenceProvidersResponseModel> resp = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * List All Embedding Inference Providers
     * List all embedding inference providers.
     * @return ApiResponse&lt;ListEmbeddingInferenceProvidersResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListEmbeddingInferenceProvidersResponseModel> listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProvidersResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List All Embedding Inference Providers (asynchronously)
     * List all embedding inference providers.
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetAsync(final ApiCallback<ListEmbeddingInferenceProvidersResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listAllEmbeddingInferenceProvidersV3ModelsEmbeddingsGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProvidersResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/models/llm_inference_providers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List All Llm Inference Providers
     * List all LLM inference providers.
     * @return ListLLMInferenceProvidersResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListLLMInferenceProvidersResponseModel listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet() throws ApiException {
        ApiResponse<ListLLMInferenceProvidersResponseModel> resp = listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * List All Llm Inference Providers
     * List all LLM inference providers.
     * @return ApiResponse&lt;ListLLMInferenceProvidersResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListLLMInferenceProvidersResponseModel> listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<ListLLMInferenceProvidersResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List All Llm Inference Providers (asynchronously)
     * List all LLM inference providers.
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetAsync(final ApiCallback<ListLLMInferenceProvidersResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListLLMInferenceProvidersResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGet
     * @param embeddingInferenceProviderId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetCall(EmbeddingInferenceProviderID embeddingInferenceProviderId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/models/embeddings/{embedding_inference_provider_id}"
            .replaceAll("\\{" + "embedding_inference_provider_id" + "\\}", apiClient.escapeString(embeddingInferenceProviderId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetValidateBeforeCall(EmbeddingInferenceProviderID embeddingInferenceProviderId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'embeddingInferenceProviderId' is set
        if (embeddingInferenceProviderId == null) {
            throw new ApiException("Missing the required parameter 'embeddingInferenceProviderId' when calling listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGet(Async)");
        }
        
        com.squareup.okhttp.Call call = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetCall(embeddingInferenceProviderId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List Embedding Inference Provider Models
     * Lists all embedding models in the provided embedding inference provider.
     * @param embeddingInferenceProviderId  (required)
     * @return ListEmbeddingInferenceProviderModelsResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListEmbeddingInferenceProviderModelsResponseModel listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGet(EmbeddingInferenceProviderID embeddingInferenceProviderId) throws ApiException {
        ApiResponse<ListEmbeddingInferenceProviderModelsResponseModel> resp = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetWithHttpInfo(embeddingInferenceProviderId);
        return resp.getData();
    }

    /**
     * List Embedding Inference Provider Models
     * Lists all embedding models in the provided embedding inference provider.
     * @param embeddingInferenceProviderId  (required)
     * @return ApiResponse&lt;ListEmbeddingInferenceProviderModelsResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListEmbeddingInferenceProviderModelsResponseModel> listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetWithHttpInfo(EmbeddingInferenceProviderID embeddingInferenceProviderId) throws ApiException {
        com.squareup.okhttp.Call call = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetValidateBeforeCall(embeddingInferenceProviderId, null, null);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProviderModelsResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List Embedding Inference Provider Models (asynchronously)
     * Lists all embedding models in the provided embedding inference provider.
     * @param embeddingInferenceProviderId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetAsync(EmbeddingInferenceProviderID embeddingInferenceProviderId, final ApiCallback<ListEmbeddingInferenceProviderModelsResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listEmbeddingInferenceProviderModelsV3ModelsEmbeddingsEmbeddingInferenceProviderIdGetValidateBeforeCall(embeddingInferenceProviderId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListEmbeddingInferenceProviderModelsResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet
     * @param llmInferenceProviderId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetCall(LLMInferenceProviderID llmInferenceProviderId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms"
            .replaceAll("\\{" + "llm_inference_provider_id" + "\\}", apiClient.escapeString(llmInferenceProviderId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetValidateBeforeCall(LLMInferenceProviderID llmInferenceProviderId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'llmInferenceProviderId' is set
        if (llmInferenceProviderId == null) {
            throw new ApiException("Missing the required parameter 'llmInferenceProviderId' when calling listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet(Async)");
        }
        
        com.squareup.okhttp.Call call = listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetCall(llmInferenceProviderId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List Llm Inference Provider Models
     * Lists all LLM models in the provided llm inference provider.
     * @param llmInferenceProviderId  (required)
     * @return ListLLMInferenceProviderModelsResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListLLMInferenceProviderModelsResponseModel listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet(LLMInferenceProviderID llmInferenceProviderId) throws ApiException {
        ApiResponse<ListLLMInferenceProviderModelsResponseModel> resp = listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetWithHttpInfo(llmInferenceProviderId);
        return resp.getData();
    }

    /**
     * List Llm Inference Provider Models
     * Lists all LLM models in the provided llm inference provider.
     * @param llmInferenceProviderId  (required)
     * @return ApiResponse&lt;ListLLMInferenceProviderModelsResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListLLMInferenceProviderModelsResponseModel> listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetWithHttpInfo(LLMInferenceProviderID llmInferenceProviderId) throws ApiException {
        com.squareup.okhttp.Call call = listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetValidateBeforeCall(llmInferenceProviderId, null, null);
        Type localVarReturnType = new TypeToken<ListLLMInferenceProviderModelsResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List Llm Inference Provider Models (asynchronously)
     * Lists all LLM models in the provided llm inference provider.
     * @param llmInferenceProviderId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetAsync(LLMInferenceProviderID llmInferenceProviderId, final ApiCallback<ListLLMInferenceProviderModelsResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetValidateBeforeCall(llmInferenceProviderId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListLLMInferenceProviderModelsResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
