/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.CreateCorpusRequestModel;
import io.swagger.client.model.CreateCorpusResponseModel;
import io.swagger.client.model.DeleteCorpusResponseModel;
import io.swagger.client.model.GetCorpusResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.ListCorporaResponseModel;
import io.swagger.client.model.ListCorpusReferenceObjectsResponseModel;
import io.swagger.client.model.UpdateCorpusRequestModel;
import io.swagger.client.model.UpdateCorpusResponseModel;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RagcorporaApi {
    private ApiClient apiClient;
    private Map<String, String> headers;

    public RagcorporaApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RagcorporaApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public void setHeadersOverrides(Map<String, String> headers) {
        this.headers = headers;
    }

    /**
     * Build call for createACorpusV3RagCorporaPost
     * @param body  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createACorpusV3RagCorporaPostCall(CreateCorpusRequestModel body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/v3/rag/corpora";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createACorpusV3RagCorporaPostValidateBeforeCall(CreateCorpusRequestModel body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling createACorpusV3RagCorporaPost(Async)");
        }
        
        com.squareup.okhttp.Call call = createACorpusV3RagCorporaPostCall(body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Create A Corpus
     * Creates a corpus.
     * @param body  (required)
     * @return CreateCorpusResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreateCorpusResponseModel createACorpusV3RagCorporaPost(CreateCorpusRequestModel body) throws ApiException {
        ApiResponse<CreateCorpusResponseModel> resp = createACorpusV3RagCorporaPostWithHttpInfo(body);
        return resp.getData();
    }

    /**
     * Create A Corpus
     * Creates a corpus.
     * @param body  (required)
     * @return ApiResponse&lt;CreateCorpusResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreateCorpusResponseModel> createACorpusV3RagCorporaPostWithHttpInfo(CreateCorpusRequestModel body) throws ApiException {
        com.squareup.okhttp.Call call = createACorpusV3RagCorporaPostValidateBeforeCall(body, null, null);
        Type localVarReturnType = new TypeToken<CreateCorpusResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Create A Corpus (asynchronously)
     * Creates a corpus.
     * @param body  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createACorpusV3RagCorporaPostAsync(CreateCorpusRequestModel body, final ApiCallback<CreateCorpusResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createACorpusV3RagCorporaPostValidateBeforeCall(body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreateCorpusResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for deleteACorpusV3RagCorporaCorpusIdDelete
     * @param corpusId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteACorpusV3RagCorporaCorpusIdDeleteCall(Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/corpora/{corpus_id}"
            .replaceAll("\\{" + "corpus_id" + "\\}", apiClient.escapeString(corpusId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteACorpusV3RagCorporaCorpusIdDeleteValidateBeforeCall(Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'corpusId' is set
        if (corpusId == null) {
            throw new ApiException("Missing the required parameter 'corpusId' when calling deleteACorpusV3RagCorporaCorpusIdDelete(Async)");
        }
        
        com.squareup.okhttp.Call call = deleteACorpusV3RagCorporaCorpusIdDeleteCall(corpusId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Delete A Corpus
     * Deletes the corpus specified in &#x60;corpus_id&#x60;.
     * @param corpusId  (required)
     * @return DeleteCorpusResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public DeleteCorpusResponseModel deleteACorpusV3RagCorporaCorpusIdDelete(Object corpusId) throws ApiException {
        ApiResponse<DeleteCorpusResponseModel> resp = deleteACorpusV3RagCorporaCorpusIdDeleteWithHttpInfo(corpusId);
        return resp.getData();
    }

    /**
     * Delete A Corpus
     * Deletes the corpus specified in &#x60;corpus_id&#x60;.
     * @param corpusId  (required)
     * @return ApiResponse&lt;DeleteCorpusResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<DeleteCorpusResponseModel> deleteACorpusV3RagCorporaCorpusIdDeleteWithHttpInfo(Object corpusId) throws ApiException {
        com.squareup.okhttp.Call call = deleteACorpusV3RagCorporaCorpusIdDeleteValidateBeforeCall(corpusId, null, null);
        Type localVarReturnType = new TypeToken<DeleteCorpusResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Delete A Corpus (asynchronously)
     * Deletes the corpus specified in &#x60;corpus_id&#x60;.
     * @param corpusId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteACorpusV3RagCorporaCorpusIdDeleteAsync(Object corpusId, final ApiCallback<DeleteCorpusResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteACorpusV3RagCorporaCorpusIdDeleteValidateBeforeCall(corpusId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<DeleteCorpusResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getACorpusV3RagCorporaCorpusIdGet
     * @param corpusId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getACorpusV3RagCorporaCorpusIdGetCall(Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/corpora/{corpus_id}"
            .replaceAll("\\{" + "corpus_id" + "\\}", apiClient.escapeString(corpusId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getACorpusV3RagCorporaCorpusIdGetValidateBeforeCall(Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'corpusId' is set
        if (corpusId == null) {
            throw new ApiException("Missing the required parameter 'corpusId' when calling getACorpusV3RagCorporaCorpusIdGet(Async)");
        }
        
        com.squareup.okhttp.Call call = getACorpusV3RagCorporaCorpusIdGetCall(corpusId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get A Corpus
     * Returns a corpus matching the provided &#x60;corpus_id&#x60;.
     * @param corpusId  (required)
     * @return GetCorpusResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public GetCorpusResponseModel getACorpusV3RagCorporaCorpusIdGet(Object corpusId) throws ApiException {
        ApiResponse<GetCorpusResponseModel> resp = getACorpusV3RagCorporaCorpusIdGetWithHttpInfo(corpusId);
        return resp.getData();
    }

    /**
     * Get A Corpus
     * Returns a corpus matching the provided &#x60;corpus_id&#x60;.
     * @param corpusId  (required)
     * @return ApiResponse&lt;GetCorpusResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<GetCorpusResponseModel> getACorpusV3RagCorporaCorpusIdGetWithHttpInfo(Object corpusId) throws ApiException {
        com.squareup.okhttp.Call call = getACorpusV3RagCorporaCorpusIdGetValidateBeforeCall(corpusId, null, null);
        Type localVarReturnType = new TypeToken<GetCorpusResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get A Corpus (asynchronously)
     * Returns a corpus matching the provided &#x60;corpus_id&#x60;.
     * @param corpusId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getACorpusV3RagCorporaCorpusIdGetAsync(Object corpusId, final ApiCallback<GetCorpusResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getACorpusV3RagCorporaCorpusIdGetValidateBeforeCall(corpusId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<GetCorpusResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listAllCorporaV3RagCorporaGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listAllCorporaV3RagCorporaGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/corpora";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listAllCorporaV3RagCorporaGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = listAllCorporaV3RagCorporaGetCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List All Corpora
     * Lists all corpora.
     * @return ListCorporaResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListCorporaResponseModel listAllCorporaV3RagCorporaGet() throws ApiException {
        ApiResponse<ListCorporaResponseModel> resp = listAllCorporaV3RagCorporaGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * List All Corpora
     * Lists all corpora.
     * @return ApiResponse&lt;ListCorporaResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListCorporaResponseModel> listAllCorporaV3RagCorporaGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = listAllCorporaV3RagCorporaGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<ListCorporaResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List All Corpora (asynchronously)
     * Lists all corpora.
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listAllCorporaV3RagCorporaGetAsync(final ApiCallback<ListCorporaResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listAllCorporaV3RagCorporaGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListCorporaResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet
     * @param corpusId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetCall(Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/corpora/{corpus_id}/reference_objects"
            .replaceAll("\\{" + "corpus_id" + "\\}", apiClient.escapeString(corpusId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetValidateBeforeCall(Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'corpusId' is set
        if (corpusId == null) {
            throw new ApiException("Missing the required parameter 'corpusId' when calling listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet(Async)");
        }
        
        com.squareup.okhttp.Call call = listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetCall(corpusId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List Corpus Reference Objects
     * Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
     * @param corpusId  (required)
     * @return ListCorpusReferenceObjectsResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListCorpusReferenceObjectsResponseModel listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet(Object corpusId) throws ApiException {
        ApiResponse<ListCorpusReferenceObjectsResponseModel> resp = listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetWithHttpInfo(corpusId);
        return resp.getData();
    }

    /**
     * List Corpus Reference Objects
     * Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
     * @param corpusId  (required)
     * @return ApiResponse&lt;ListCorpusReferenceObjectsResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListCorpusReferenceObjectsResponseModel> listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetWithHttpInfo(Object corpusId) throws ApiException {
        com.squareup.okhttp.Call call = listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetValidateBeforeCall(corpusId, null, null);
        Type localVarReturnType = new TypeToken<ListCorpusReferenceObjectsResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List Corpus Reference Objects (asynchronously)
     * Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
     * @param corpusId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetAsync(Object corpusId, final ApiCallback<ListCorpusReferenceObjectsResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetValidateBeforeCall(corpusId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListCorpusReferenceObjectsResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for updateACorpusV3RagCorporaCorpusIdPatch
     * @param body  (required)
     * @param corpusId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call updateACorpusV3RagCorporaCorpusIdPatchCall(UpdateCorpusRequestModel body, Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/v3/rag/corpora/{corpus_id}"
            .replaceAll("\\{" + "corpus_id" + "\\}", apiClient.escapeString(corpusId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call updateACorpusV3RagCorporaCorpusIdPatchValidateBeforeCall(UpdateCorpusRequestModel body, Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling updateACorpusV3RagCorporaCorpusIdPatch(Async)");
        }
        // verify the required parameter 'corpusId' is set
        if (corpusId == null) {
            throw new ApiException("Missing the required parameter 'corpusId' when calling updateACorpusV3RagCorporaCorpusIdPatch(Async)");
        }
        
        com.squareup.okhttp.Call call = updateACorpusV3RagCorporaCorpusIdPatchCall(body, corpusId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update A Corpus
     * Updates the corpus specified in &#x60;corpus_id&#x60;.
     * @param body  (required)
     * @param corpusId  (required)
     * @return UpdateCorpusResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public UpdateCorpusResponseModel updateACorpusV3RagCorporaCorpusIdPatch(UpdateCorpusRequestModel body, Object corpusId) throws ApiException {
        ApiResponse<UpdateCorpusResponseModel> resp = updateACorpusV3RagCorporaCorpusIdPatchWithHttpInfo(body, corpusId);
        return resp.getData();
    }

    /**
     * Update A Corpus
     * Updates the corpus specified in &#x60;corpus_id&#x60;.
     * @param body  (required)
     * @param corpusId  (required)
     * @return ApiResponse&lt;UpdateCorpusResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<UpdateCorpusResponseModel> updateACorpusV3RagCorporaCorpusIdPatchWithHttpInfo(UpdateCorpusRequestModel body, Object corpusId) throws ApiException {
        com.squareup.okhttp.Call call = updateACorpusV3RagCorporaCorpusIdPatchValidateBeforeCall(body, corpusId, null, null);
        Type localVarReturnType = new TypeToken<UpdateCorpusResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Update A Corpus (asynchronously)
     * Updates the corpus specified in &#x60;corpus_id&#x60;.
     * @param body  (required)
     * @param corpusId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call updateACorpusV3RagCorporaCorpusIdPatchAsync(UpdateCorpusRequestModel body, Object corpusId, final ApiCallback<UpdateCorpusResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = updateACorpusV3RagCorporaCorpusIdPatchValidateBeforeCall(body, corpusId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<UpdateCorpusResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
