/*
 * Kenja AI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.CreateReferenceObjectResponseModel;
import io.swagger.client.model.DeleteReferenceObjectResponseModel;
import io.swagger.client.model.GetReferenceObjectResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.ListReferenceObjectsResponseModel;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RagreferenceObjectsApi {
    private ApiClient apiClient;
    private Map<String, String> headers;

    public RagreferenceObjectsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RagreferenceObjectsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public void setHeadersOverrides(Map<String, String> headers) {
        this.headers = headers;
    }

    /**
     * Build call for createsAReferenceObjectV3RagReferenceObjectsPost
     * @param uploadFile  (required)
     * @param corpusId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createsAReferenceObjectV3RagReferenceObjectsPostCall(Object uploadFile, Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/reference_objects";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (corpusId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("corpus_id", corpusId));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (uploadFile != null)
        localVarFormParams.put("upload_file", uploadFile);

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createsAReferenceObjectV3RagReferenceObjectsPostValidateBeforeCall(Object uploadFile, Object corpusId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'uploadFile' is set
        if (uploadFile == null) {
            throw new ApiException("Missing the required parameter 'uploadFile' when calling createsAReferenceObjectV3RagReferenceObjectsPost(Async)");
        }
        // verify the required parameter 'corpusId' is set
        if (corpusId == null) {
            throw new ApiException("Missing the required parameter 'corpusId' when calling createsAReferenceObjectV3RagReferenceObjectsPost(Async)");
        }
        
        com.squareup.okhttp.Call call = createsAReferenceObjectV3RagReferenceObjectsPostCall(uploadFile, corpusId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Creates A Reference Object
     * Creates an reference object.
     * @param uploadFile  (required)
     * @param corpusId  (required)
     * @return CreateReferenceObjectResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreateReferenceObjectResponseModel createsAReferenceObjectV3RagReferenceObjectsPost(Object uploadFile, Object corpusId) throws ApiException {
        ApiResponse<CreateReferenceObjectResponseModel> resp = createsAReferenceObjectV3RagReferenceObjectsPostWithHttpInfo(uploadFile, corpusId);
        return resp.getData();
    }

    /**
     * Creates A Reference Object
     * Creates an reference object.
     * @param uploadFile  (required)
     * @param corpusId  (required)
     * @return ApiResponse&lt;CreateReferenceObjectResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreateReferenceObjectResponseModel> createsAReferenceObjectV3RagReferenceObjectsPostWithHttpInfo(Object uploadFile, Object corpusId) throws ApiException {
        com.squareup.okhttp.Call call = createsAReferenceObjectV3RagReferenceObjectsPostValidateBeforeCall(uploadFile, corpusId, null, null);
        Type localVarReturnType = new TypeToken<CreateReferenceObjectResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Creates A Reference Object (asynchronously)
     * Creates an reference object.
     * @param uploadFile  (required)
     * @param corpusId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createsAReferenceObjectV3RagReferenceObjectsPostAsync(Object uploadFile, Object corpusId, final ApiCallback<CreateReferenceObjectResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createsAReferenceObjectV3RagReferenceObjectsPostValidateBeforeCall(uploadFile, corpusId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreateReferenceObjectResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDelete
     * @param referenceObjectId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteCall(Object referenceObjectId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/reference_objects/{reference_object_id}"
            .replaceAll("\\{" + "reference_object_id" + "\\}", apiClient.escapeString(referenceObjectId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteValidateBeforeCall(Object referenceObjectId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'referenceObjectId' is set
        if (referenceObjectId == null) {
            throw new ApiException("Missing the required parameter 'referenceObjectId' when calling deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDelete(Async)");
        }
        
        com.squareup.okhttp.Call call = deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteCall(referenceObjectId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Deletes A Reference Object
     * Deletes the reference object specified in &#x60;reference_object_id&#x60;.
     * @param referenceObjectId  (required)
     * @return DeleteReferenceObjectResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public DeleteReferenceObjectResponseModel deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDelete(Object referenceObjectId) throws ApiException {
        ApiResponse<DeleteReferenceObjectResponseModel> resp = deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteWithHttpInfo(referenceObjectId);
        return resp.getData();
    }

    /**
     * Deletes A Reference Object
     * Deletes the reference object specified in &#x60;reference_object_id&#x60;.
     * @param referenceObjectId  (required)
     * @return ApiResponse&lt;DeleteReferenceObjectResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<DeleteReferenceObjectResponseModel> deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteWithHttpInfo(Object referenceObjectId) throws ApiException {
        com.squareup.okhttp.Call call = deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteValidateBeforeCall(referenceObjectId, null, null);
        Type localVarReturnType = new TypeToken<DeleteReferenceObjectResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Deletes A Reference Object (asynchronously)
     * Deletes the reference object specified in &#x60;reference_object_id&#x60;.
     * @param referenceObjectId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteAsync(Object referenceObjectId, final ApiCallback<DeleteReferenceObjectResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteValidateBeforeCall(referenceObjectId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<DeleteReferenceObjectResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGet
     * @param referenceObjectId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetCall(Object referenceObjectId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/reference_objects/{reference_object_id}"
            .replaceAll("\\{" + "reference_object_id" + "\\}", apiClient.escapeString(referenceObjectId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetValidateBeforeCall(Object referenceObjectId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'referenceObjectId' is set
        if (referenceObjectId == null) {
            throw new ApiException("Missing the required parameter 'referenceObjectId' when calling getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGet(Async)");
        }
        
        com.squareup.okhttp.Call call = getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetCall(referenceObjectId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get A Reference Object
     * Returns a reference object matching the provided &#x60;reference_object_id&#x60;.
     * @param referenceObjectId  (required)
     * @return GetReferenceObjectResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public GetReferenceObjectResponseModel getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGet(Object referenceObjectId) throws ApiException {
        ApiResponse<GetReferenceObjectResponseModel> resp = getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetWithHttpInfo(referenceObjectId);
        return resp.getData();
    }

    /**
     * Get A Reference Object
     * Returns a reference object matching the provided &#x60;reference_object_id&#x60;.
     * @param referenceObjectId  (required)
     * @return ApiResponse&lt;GetReferenceObjectResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<GetReferenceObjectResponseModel> getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetWithHttpInfo(Object referenceObjectId) throws ApiException {
        com.squareup.okhttp.Call call = getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetValidateBeforeCall(referenceObjectId, null, null);
        Type localVarReturnType = new TypeToken<GetReferenceObjectResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get A Reference Object (asynchronously)
     * Returns a reference object matching the provided &#x60;reference_object_id&#x60;.
     * @param referenceObjectId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetAsync(Object referenceObjectId, final ApiCallback<GetReferenceObjectResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetValidateBeforeCall(referenceObjectId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<GetReferenceObjectResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listsAllReferenceObjectsV3RagReferenceObjectsGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listsAllReferenceObjectsV3RagReferenceObjectsGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v3/rag/reference_objects";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listsAllReferenceObjectsV3RagReferenceObjectsGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = listsAllReferenceObjectsV3RagReferenceObjectsGetCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Lists All Reference Objects
     * Lists all corpora.
     * @return ListReferenceObjectsResponseModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ListReferenceObjectsResponseModel listsAllReferenceObjectsV3RagReferenceObjectsGet() throws ApiException {
        ApiResponse<ListReferenceObjectsResponseModel> resp = listsAllReferenceObjectsV3RagReferenceObjectsGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * Lists All Reference Objects
     * Lists all corpora.
     * @return ApiResponse&lt;ListReferenceObjectsResponseModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ListReferenceObjectsResponseModel> listsAllReferenceObjectsV3RagReferenceObjectsGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = listsAllReferenceObjectsV3RagReferenceObjectsGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<ListReferenceObjectsResponseModel>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Lists All Reference Objects (asynchronously)
     * Lists all corpora.
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listsAllReferenceObjectsV3RagReferenceObjectsGetAsync(final ApiCallback<ListReferenceObjectsResponseModel> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listsAllReferenceObjectsV3RagReferenceObjectsGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ListReferenceObjectsResponseModel>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
